C...................................................................... 
C.....SUBROUTINE ELIMBM CALCULATES THE BASEMAT FORWARD ELIMINATION 
C.....COEFFICIENTS NEEDED FOR SOLVING THE CONSERVATION OF MASS AND 
C.....ENERGY EQS. IN THE SPREADING MELT.  THE SUBROUTINE ALSO CALCULATES
C.....GAS VELOCITY DERIVATIVE FUNCTIONS NEEDED FOR OXIDATION REACTION
C.....EVALUATIONS. MELT/SUBSTRATE BOUNDARY CONDITIONS TREATED HERE ARE:     
C.....NBCINT=1:  NO CRUST, NO ABLATION; CONVECTION OR MIXING. 
C.....NBCINT=2:  STABLE CRUST GROWTH.     
C.....NBCINT=3:  STATIONARY (NON-GROWING) CRUST.    
C.....NBCINT=4:  ABLATION WITH NO CRUST; SLAG CONTINUOUSLY MIXED OFF    
C..... SURFACE.
C.....NBCINT=5:  ABLATION WITH NO CRUST; SLAG REMAINS ON SURFACE AS FILM
C.....NBCINT=6:  SIMULTANEOUS CRUST GROWTH OVER ABLATING SUBSTRATE; THE 
C..... CRUST IS POROUS SUCH THAT SLAG CONTINOUSLY DRAINS      
C..... THROUGH THE GROWING CRUST.
C.....NBCINT=7:  STATIONARY POROUS CRUST OVER ABLATING SUBSTRATE.
C.....NBCINT=8:  GROWING NON-POROUS CRUST OVER ABLATING SUBSTRATE.  THE 
C..... SLAG REMAINS AS A MOLTEN FILM BENEATH CRUST. 
C.....NBCINT=9:  STATIONARY NONPOROUS CRUST OVER ABLATING SUBSTRATE.    
C...................................................................... 
      SUBROUTINE ELIMBM
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON /WATVARS/FCRUST(999),VLW(999),VLWOLD(999),DWAT(999),
     1DWATOLD(999),EWAT(999),EWATOLD(999),TWAT(999),CORDDC(999),
     2DSRDC(999),DHDC(999),TSRDC,TINTDC,HWATB(999),TSURFW(999),XMS(999),
     3XMST,XINTS,ESRDTW(999),TSRDTW(999),DSRDTW(999),TSRDW,TINTDW,
     4TWATI,ELDCO(999),ELDCX(999,99),CRDCX(999,99),TIMINJ(999,99),
     5XDTINJ(999,99),TDTINJ(999,99),ELWATI,XMWAT,XMWATO,XBALW,
     6HDRY(999),EINTW,XMCT(199),XMCDT(16,999),TMPCDT(999),CMPCDT(999),
     7FDC(999),FCOV(999),FBED(999),FHEAT(999),XFACJ(999),
     8XMBEDJ(16,999),XMBEDJT(999),PBED,QBED(999),QWATER(999),
     9QSURFACE(999),QWATERT(999),HBED(999),POROSBED,XMCRDT(16,999),
     1XMCRT(999),XMBDINT(999),XMT(999)
      COMMON/CATCHR/A(999),B(999),C(999),D(999),P(999),Q(999),
     1RECON(999),DELVEL(999),DSRDT(999),DELHTS(999),EMAX(999,999),
     2DBLKEN(999),DELHIT(16,999),SOURCE(16,999),SRCTOT(999),
     3HCROLD(16,999),DCDOT(999),HCRUST(16,999),DFILM(16,999),
     4DFMOLD(16,999),DENOLD(999),SIGOX(999),SIGCON(999),BET(999),
     5TFZX(999),TFZC(999),TKX(999),TKM(999),THETO(999,999),
     6THET1(999,999),OMEG0(4,999),OMEG1(4,999),TAO0(999),TAO1(999),
     7SIG0(999),SIG1(999),TARGB(999),DADOT(999),DADOTG(999),
     8XLOLD(4,999),VISREX(999),TATMS(999),HTMP(999),DHTMP(999),
     9HTMOLD(999)
      COMMON/CATCHI/NUMS(4,999),NUMOLD(4,999),NTRACK(16),NSUMP(999),
     1NPASSG(999),NCRSTM(999),NCRRT(999),NPASS(999),NBURN,NBURNO     
      COMMON/PRINTB/ELEVAT(999),ELOLD(999),XDIST(999,999),XBTW(999,999),
     1TEMP(999,999),ENTHP(999,999),EOLD(999,999),ENBLK(999),EBKOLD(999),
     2TBULK(999),HITE(16,999),HITOLD(16,999),HTOT(999),HTOLD(999),
     3HTCFT(999),HTCOEF(999),QFLUXT(999),QFLUXB(999),VEL(999),ELO(999),
     4VELOLD(999),SRSCOR(16),AREA(999),RAD(999),ARC(999),VOLCN(16),
     5VOID(999),VGJ(999),ZABLAT(999),ZABOLD(999),DCRUST(999),
     6DCROLD(999),DABCON(999),DABOLD(999),DFILMT(999),DFOLT(999),
     7SMFLX(4,999),XLSMF(4,999),TOTVOL,XFACMS(999),XMFLXA,XMCORT,
     8VCORT,TOTOX,TOTMET,QFLXT,QFLXB,TIME,DTIME,XMCOR(16),VCOR(16),
     9TCONI,RSAND,HDOWNC,TBOUND,EMISCN,PDRYWL,XDISTO(999),QOXT(999),
     1XLENSH,XBTWO(999),RCOMP,WDOOR,RSUMP,RSHELL,RPED,TPED,ELSMP,
     1TENDP(10,999),TFRZSH,TDEBRS,TKDEBR,PDEBR,CPDEBR,ENENDP(10,999),
     2ENOLDP(10,999),DXVERT,DXSNK,XDSTE(10,999),XBTE(10,999),HXLA(999),
     3HXLB(999),TSFEB(999),DCRS(999),DCRSLD(999),HCRS(16,999),
     4HCRSLD(16,999),THETE0(10,999),THETE1(10,999),QSHELL,QSHELE,TSHELI,
     5SIGOXE(999),FKOXE(999),RINJC,XLSEC,ANGSEC,ANINJC,XLCHAN,WCHNL,
     6TEFZX(999),TIMSPC(999),DXNODE(999),TNORM(999),FRCSOL(999),
     7ALPSPR(999),CRAMCON,HINTF,TSHLMX,XFRMX(999),XFROX(999),XFRTX(999),
     8XMLMX(999),XMLOX(999),XMLTX(999),XTOTX(999),TIMEO,TMAX,EDOWN(999),
     9HCP(999)
      COMMON/PROPI/ NMATC,NMATFI,NMATFF,ICAOH2,ICACO3,IMCCO3,IFH2O,     
     1IVH2O,ICK2O,IVK2O,INA2O,ITIO2,ISIO2,ICAO,IMGO,IAL2O3,IFEO,IFE2O3, 
     2IFE3O4,IFE,ICR,INI,IZR,IU,IB4C,IB,ICR2O3,INIO,IUO2,IZRO2,IB2O3,   
     3NBCINT(999),NODES(999),NUMNOD,IMOX(28),IBAS,ILCS,ILL,NACTIV(999),     
     4NBFRZM,NBFRZO,NABLFM,NDRNFM,NTYPMT(999,999),NDOOR,NBMADJ,NUMSHV,   
     5NBSHL(999),NCRSTS(999),NUMSHH,NSKIPE,NACSH,NWAT,NPEND,NBCBOT,
     6NCRTOP,NBFZOE,NBFZME,NGEOM,NL(999,999),NFRSCT,NLOGSH,NADAB,NINVIS,
     7NSIMST,NSTEEL,NOVHT,NOVTK,NOVUM,NOVEM,NOVSIG,NPLLOC(999),NBPL,
     8IXP(999),IYP(999),NVTPE,NSOLTP,NSOLF,NINTF,IFLGA(999),ICTYPE,ICTC,
     9NPOURS,NSMP,NPED,NDOR,NSHL,NANULS,NSMPCV,NBOIL,NSWALL,NMVER,
     1NCRTEM,NTHINC,NVELP,NITMAX,NENMAX,NPRINT,NPFREQ,NTIMSPC,NPLFREQ,
     2NPLTOT,NJET,NJETP,NJETD,NJETND,NODCAP,NVELPW,NITMAXW,NENMXW,
     3IFLGJ(999),NBEDCQ,ISHELE
      COMMON/PRINTR/ QFEH2O,QCRH2O,QZRH2O,QFECO2,QCRCO2,QZRCO2,
     4XFH2OU,XFCAOH,XFMGCA,XFCACO,XZRMRE,XFEMRE,XCRMRE,XZRORE,XFEORE,   
     5XCRORE,XMH2O,XMCO2,XMCACO,XMMGCA,XMCAOH,TFWL,TFWS,TBWL,TBWS,      
     6TMCAL,TMCAS,TCAL,TCAS,TFOS,TFOL,TFMS,TFML,XVISC(28),SVISC(28),    
     7XMOL(28),FMMOL(28),ROM(28),ROMLIQ(28),AEQM(28,2),BEQM(28,2),
     8CEQM(28,2),ECL,ECS,ECAL,ECAS,EMCAL,EMCAS,EBWL,EBWS,EFWL,EFWS,    
     9STEF,GRAV,PI,TCS,TCL,CCL,CCS,RMASSL,WPCC,WPM,WPA,WPCS,ROC,RMASSS,   
     1ANGSHL,RSLAGL,RSLAGS,HNODT,VFAV,VGAV,QXAV,XWTSS(16),  
     2TSCS(2),TSCL(2),ESCS(2),ESCL(2),CCSS(2),CCSL(2),ROSTLS,ROSTLL,
     3XFRGAS,HMINC,TST(99),TSTOP(99),AINTP(99),BINTP(99),DRATIO(999),
     4XBCN(999),XDCN(999),XBLT(15),ADEC(99),BDEC(99),APOUR(16,99),
     5BPOUR(16,99),XWTC(14),BWIDTH,THCKCV,TMBOIL,TEBOIL,VFINT,ANGFAN,
     6ALPMAX,THSHL,XFCABL,XNDMIN,DVMX,DAVMX,DEAVMX,DEMX,TDC,QDCU,QDCUO2,
     7TSINJ,EINJ,DTINJ,TKINJ,ROEV,CPINJ,SURFT,VSINJ,EMINJ,TSINJO,EINJO,
     8DTINJO,TKINJO,ROEVO,CPINJO,SURFTO,VSINJO,EMINJO,XLEADE,ARSUM,
     9DBUBOX,UTRISE,TREMSH,DJET,DFALL,WEBER,FROUDE,XPSAITO,XPEPSTN,
     1FRAG,XMBEDT,XMBED(16),XLPENT,XLPENA,UJET,UFALL,HFALL,ERPV,
     2TJETT(99),DJETT(99),HWATP,XDOTJET,DVMXW,DAVMXW,DEMXW,DEAVMXW,
     3QJETW,XSTMJF,TINTSJF,ESAT,DRDOOR,DRANL,EI,QDCBUO2,QDCBU,
     4EBEDS,EBEDB
      COMMON/BASPR/ HBMT(999,999,16),HBMOLD(999,999,16) 
      COMMON/PROPB/CPBM(999),FKB(999,999),DENB(999,999),DTDEB(999,999),
     1EMIBM(999),DENCRS(999),ENCRS(999),FKRF(999),DENRF(999),CPRF(999) 
      COMMON/PROPM/DTDEM(999),CPMLT(999),FKMLT(999),DENMLT(999),
     1SIGMLT(999),UMMLT(999),EMIMLT(999)      
      DO 85 J=1,NUMNOD
      IF(NACTIV(J).EQ.0.OR.NADAB.EQ.1) GO TO 85
      BATEVL=BET(J)   
      IF(NSMPCV.EQ.1.AND.NBURN.EQ.0.AND.J.LE.NSMP) BATEVL=0.D0
      A(1)=0.D0
      B(1)=1.D0
      C(1)=0.D0
      D(1)=0.D0
C.....ASSIGN THE DERIVATIVE OF MELT TEMPERATURE WITH RESPECT TO
C.....ENTHALPY AND ALSO EFFECTIVE HEAT TRANSFER COEFFICIENT TO BASEMAT
C.....DEPENDING UPON WATER AVAILABILITY AND PRESENCE/ABSENCE OF MELT.
      IF(HTMP(J).LE.0.D0) GO TO 432
      ALPBLK=DTDEM(J) 
      HTBMEF=HTCOEF(J)
      GO TO 433
  432 CONTINUE
      ALPBLK=0.D0     
      HTBMEF=FCRUST(J)*HTCOEF(J)
      IF(NWAT.EQ.2) HTBMEF=DMAX1(HTBMEF,HDRY(J))
  433 CONTINUE
C.....ASSIGN PHYSICAL PROPERTIES AT INTERFACIAL NODES FOR CRUSTING/     
C.....ABLATION CASES. 
      IF(NBCINT(J).GT.3) GO TO 703
      NDRIVE=2
      IF(NTYPMT(1,J).GT.3) GO TO 5090     
      SDECAY=0.D0     
      GO TO 5091      
 5090 CONTINUE
      SDECAY=ROM(21)*QDCU*HBMT(1,J,6)+ROM(26)*QDCUO2*HBMT(1,J,15)
 5091 CONTINUE
      DEN1=DENB(1,J)  
      TK1=FKB(1,J)    
      TKJ=TK1
      DTDE1=DTDEB(1,J)
      ALPJ=DTDE1      
      DEN2=DENB(2,J)  
      TK2=FKB(2,J)    
      IF(NSMPCV.EQ.1.AND.NBURN.EQ.0.AND.J.LE.NSMP) TK2=0.D0   
      TKJP1=TK2
      DTDE2=DTDEB(2,J)
      ALPJP1=DTDE2    
      GO TO(91,92,93),NBCINT(J) 
  703 CONTINUE
      NDRIVE=3
      IF(NTYPMT(2,J).GT.3) GO TO 53
      SDECAY=0.D0     
      GO TO 54
   53 CONTINUE
      SDECAY=ROM(21)*QDCU*HBMT(2,J,6)+ROM(26)*QDCUO2*HBMT(2,J,15)
   54 CONTINUE
      DEN1=DENB(1,J)  
      DEN2=DENB(2,J)  
      TK1=FKB(1,J)    
      TK2=FKB(2,J)    
      IF(NSMPCV.EQ.1.AND.NBURN.EQ.0.AND.J.LE.NSMP) TK2=0.D0   
      DTDE1=DTDEB(1,J)
      DTDE2=DTDEB(2,J)
      TKJ=TK2
      ALPJ=DTDE2      
      IRUT=NBCINT(J)-3
      GO TO (94,95,96,97,98,99),IRUT      
   91 CONTINUE
      COND=(TK1*TK2)/(TK1*(XDIST(1,J)-XBTW(1,J))+TK2*XBTW(1,J))
      A(1)=(XBTW(1,J)*DEN1*(ENTHP(1,J)-EOLD(1,J)))/DTIME-HTBMEF*     
     1(TARGB(J)-TEMP(1,J))+COND*(TEMP(1,J)-TEMP(2,J))-SDECAY  
      B(1)=(XBTW(1,J)*DEN1)/DTIME+(HTBMEF+COND)*DTDE1      
      C(1)=-HTBMEF*ALPBLK    
      D(1)=COND*DTDE2 
      DADOTG(J)=0.D0  
      DADOT(J)=0.D0   
      DCDOT(J)=0.D0   
      BS0=0.D0
      AS1=0.D0
      BS1=0.D0
      BT0=0.D0
      AT1=0.D0
      BT1=0.D0
      WJP1=0.D0
      WBLK=0.D0
      FBLK=0.D0
      FBLKG=0.D0      
      FJP1=0.D0
      FJP1G=0.D0      
      GO TO 100
   92 CONTINUE
      IF(NCRRT(J).EQ.2) GO TO 93
      Z1=((HTBMEF*(TBULK(J)-TFZX(J)))/SIGOX(J))**2
      Z2=DCROLD(J)*DCROLD(J)+(TKX(J)*(TFZX(J)-TEMP(1,J)))/SIGOX(J)      
      GAM=SQRT(Z1+4.D0*Z2)      
      WJP1=-TKX(J)/(SIGOX(J)*GAM)
      WBLK=0.5D0*(((TBULK(J)-TFZX(J))*HTBMEF**2)/(GAM*SIGOX(J)**2)   
     1-HTBMEF/SIGOX(J))      
      A(1)=(XBTW(1,J)*DEN1*(ENTHP(1,J)-EOLD(1,J)))/DTIME-(TKX(J)*(TFZX(J
     1)-TEMP(1,J)))/DCRUST(J)+COND*(TEMP(1,J)-TEMP(2,J))-SDECAY
      B(1)=(XBTW(1,J)*DEN1)/DTIME+(COND+(TKX(J)*WJP1*(TFZX(J)-TEMP(1,J))
     1)/DCRUST(J)**2+TKX(J)/DCRUST(J))*DTDE1
      C(1)=(TKX(J)*(TFZX(J)-TEMP(1,J))*WBLK*ALPBLK)/DCRUST(J)**2
      D(1)=COND*DTDE2 
      DADOT(J)=0.D0   
      DADOTG(J)=0.D0  
      ZX1=TKX(J)/(2.D0*DTIME*SIGOX(J))    
      ZX2=HTBMEF/(2.D0*DTIME*SIGOX(J)) 
      DCDOT(J)=(ZX1*(TFZX(J)-TEMP(1,J)))/DCRUST(J)-ZX2*(TBULK(J)-TFZX(J)
     1)     
      FBLK=-(ZX1*(TFZX(J)-TEMP(1,J))*WBLK)/DCRUST(J)**2-ZX2   
      FJP1=-(ZX1*(TFZX(J)-TEMP(1,J))*WJP1)/DCRUST(J)**2-ZX1/DCRUST(J)   
      FBLKG=0.D0      
      FJP1G=0.D0      
      BS0=FJP1*DTDE1  
      AS1=FBLK*ALPBLK 
      BS1=FJP1*DTDE1  
      BT0=0.D0
      AT1=0.D0
      BT1=0.D0
      WJP1=0.D0
      WBLK=0.D0
      GO TO 100
   93 CONTINUE
      COND=(TK1*TK2)/(TK1*(XDIST(1,J)-XBTW(1,J))+TK2*XBTW(1,J))
      A(1)=(XBTW(1,J)*DEN1*(ENTHP(1,J)-EOLD(1,J)))/DTIME-HTBMEF*(TARG
     1B(J)-TFZX(J))+COND*(TEMP(1,J)-TEMP(2,J))-SDECAY
      B(1)=(XBTW(1,J)*DEN1)/DTIME+COND*DTDE1
      C(1)=-HTBMEF*ALPBLK    
      D(1)=COND*DTDE2 
      DADOT(J)=0.D0   
      DCDOT(J)=0.D0   
      DADOTG(J)=0.D0  
      BS0=0.D0
      AS1=0.D0
      BS1=0.D0
      BT0=0.D0
      AT1=0.D0
      BT1=0.D0
      WJP1=0.D0
      WBLK=0.D0
      FBLK=0.D0
      FBLKG=0.D0      
      FJP1=0.D0
      FJP1G=0.D0      
      GO TO 100
   94 CONTINUE
      Z1=((HTBMEF*(TBULK(J)-TFZC(J)))/SIGCON(J))**2
      Z2=ZABOLD(J)**2+(BATEVL*(TFZC(J)-TEMP(2,J)))/SIGCON(J)  
      GAM=SQRT(Z1+4.D0*Z2)      
      WJP1=-BATEVL/(SIGCON(J)*GAM)
      WBLK=0.5D0*(((TBULK(J)-TFZC(J))*HTBMEF**2)/(GAM*SIGCON(J)**2)  
     1-HTBMEF/SIGCON(J))     
      DCDOT(J)=0.D0   
      ZX1=BATEVL/(2.D0*DTIME*SIGCON(J))   
      ZX2=HTBMEF/(2.D0*DTIME*SIGCON(J))
      DADOT(J)=(ZX1*(TFZC(J)-TEMP(2,J)))/ZABLAT(J)-ZX2*(TBULK(J)-TFZC(J)
     1)     
      DADOTG(J)=DADOT(J)
      DCDOT(J)=0.D0   
      FBLK=-(ZX1*(TFZC(J)-TEMP(2,J))*WBLK)/ZABLAT(J)**2-ZX2   
      FJP1=-(ZX1*(TFZC(J)-TEMP(2,J))*WJP1)/ZABLAT(J)**2-ZX1/ZABLAT(J)   
      FBLKG=FBLK      
      FJP1G=FJP1      
      BS0=0.D0
      AS1=0.D0
      BS1=0.D0
      BT0=FJP1*DTDE2  
      AT1=FBLK*ALPBLK 
      BT1=FJP1*DTDE2  
      GO TO 101
   95 CONTINUE
      HEFF=(TKM(J)*HTBMEF)/(TKM(J)+DFILMT(J)*HTBMEF)    
      Z1=((HEFF*(TBULK(J)-TFZC(J)))/SIGCON(J))**2   
      Z2=ZABOLD(J)**2+(BATEVL*(TFZC(J)-TEMP(2,J)))/SIGCON(J)  
      GAM=SQRT(Z1+4.D0*Z2)      
      Z3=1.D0-(HEFF*(TBULK(J)-TFZC(J)))/(GAM*SIGCON(J))
      WBLK=-(HEFF*Z3)/(2.D0*SIGCON(J))    
      WJP1=-BATEVL/(GAM*SIGCON(J))
      ZX1=BATEVL/(2.D0*DTIME*SIGCON(J))   
      ZX2=HEFF/(2.D0*DTIME*SIGCON(J))     
      DADOTG(J)=(ZX1*(TFZC(J)-TEMP(2,J)))/ZABLAT(J)-ZX2*(TBULK(J)-TFZC(J
     1))    
      DADOT(J)=0.D0   
      DCDOT(J)=0.D0   
      FBLKG=-(ZX1*(TFZC(J)-TEMP(2,J))*WBLK)/ZABLAT(J)**2-ZX2  
      FBLK=0.D0
      FJP1G=-(ZX1*(TFZC(J)-TEMP(2,J))*WJP1)/ZABLAT(J)**2-ZX1/ZABLAT(J)  
      FJP1=0.D0
      BS0=0.D0
      AS1=0.D0
      BS1=0.D0
      BT0=0.D0
      AT1=0.D0
      BT1=0.D0
      GO TO 101
   96 CONTINUE
      IF(NCRRT(J).EQ.2) GO TO 97
      F3=((TKX(J)*(TFZX(J)-TFZC(J)))/(SIGCON(J)*DCRUST(J)))**2
      F4=ZABOLD(J)**2+(BATEVL*(TFZC(J)-TEMP(2,J)))/SIGCON(J)  
      GAMCON=SQRT(F3+4.D0*F4)   
      WJP1=-BATEVL/(SIGCON(J)*GAMCON)     
      F1=((HTBMEF*(TBULK(J)-TFZX(J)))/SIGOX(J))**2
      F2=DCROLD(J)**2+(TKX(J)*(TFZX(J)-TFZC(J)))/SIGOX(J)     
      GAMOX=SQRT(F1+4.D0*F2)    
      F8=((TBULK(J)-TFZX(J))/GAMOX)*(HTBMEF/SIGOX(J))**2   
      WBLKO=0.5D0*(F8-HTBMEF/SIGOX(J)) 
      F9=(TKX(J)*(TFZX(J)-TFZC(J)))/(SIGCON(J)*DCRUST(J)**2)  
      F10=(TKX(J)*(TFZX(J)-TFZC(J)))/(GAMCON*SIGCON(J)*DCRUST(J))
      WBLK=0.5D0*F9*WBLKO*(1.D0-F10)      
      ZX1O=TKX(J)/(2.D0*DTIME*SIGOX(J))   
      ZX2O=HTBMEF/(2.D0*DTIME*SIGOX(J))
      ZX1A=BATEVL/(2.D0*DTIME*SIGCON(J))  
      ZX2A=TKX(J)/(2.D0*DTIME*SIGCON(J))  
      DCDOT(J)=(ZX1O*(TFZX(J)-TFZC(J)))/DCRUST(J)-ZX2O*(TBULK(J)-TFZX(J)
     1)     
      DADOT(J)=(ZX1A*(TFZC(J)-TEMP(2,J)))/ZABLAT(J)-(ZX2A*(TFZX(J)-TFZC(
     1J)))/DCRUST(J)  
      DADOTG(J)=DADOT(J)
      FBLKO=-(ZX1O*(TFZX(J)-TFZC(J))*WBLKO)/DCRUST(J)**2-ZX2O 
      FBLK=-(ZX1A*(TFZC(J)-TEMP(2,J))*WBLK)/ZABLAT(J)**2+(ZX2A*(TFZX(J)-
     1TFZC(J))*WBLKO)/DCRUST(J)**2
      FBLKG=FBLK      
      FJP1=-(ZX1A*(TFZC(J)-TEMP(2,J))*WJP1)/ZABLAT(J)**2-ZX1A/ZABLAT(J) 
      FJP1G=FJP1      
      BS0=0.D0
      AS1=FBLKO*ALPBLK
      BS1=0.D0
      BT0=FJP1*DTDE2  
      AT1=FBLK*ALPBLK 
      BT1=FJP1*DTDE2  
      GO TO 101
   97 CONTINUE
      Z1=((HTBMEF*(TBULK(J)-TFZC(J)))/SIGCON(J))**2
      Z2=ZABOLD(J)**2+(BATEVL*(TFZC(J)-TEMP(2,J)))/SIGCON(J)  
      GAMCON=SQRT(Z1+4.D0*Z2)   
      WBLK=0.5D0*(((TBULK(J)-TFZC(J))*HTBMEF**2)/(GAMCON*SIGCON(J)**2
     1)-HTBMEF/SIGCON(J))    
      WJP1=-BATEVL/(SIGCON(J)*GAMCON)     
      ZX1=BATEVL/(2.D0*DTIME*SIGCON(J))   
      ZX2=HTBMEF/(2.D0*DTIME*SIGCON(J))
      DADOT(J)=(ZX1*(TFZC(J)-TEMP(2,J)))/ZABLAT(J)-ZX2*(TBULK(J)-TFZX(J)
     1)     
      DADOTG(J)=DADOT(J)
      DCDOT(J)=0.D0   
      FJP1=-(ZX1*(TFZC(J)-TEMP(2,J))*WJP1)/ZABLAT(J)**2-ZX1/ZABLAT(J)   
      FJP1G=FJP1      
      FBLK=-(ZX1*(TFZC(J)-TEMP(2,J))*WBLK)/ZABLAT(J)**2
      FBLKG=FBLK      
      BS0=0.D0
      AS1=0.D0
      BS1=0.D0
      BT0=FJP1*DTDE2  
      AT1=FBLK*ALPBLK 
      BT1=FJP1*DTDE2  
      GO TO 101
   98 CONTINUE
      IF(NCRRT(J).EQ.2) GO TO 99
      TKEFF=(TKX(J)*TKM(J)*DCRUST(J))/(TKX(J)*DFILMT(J)+TKM(J)*DCRUST(J)
     1)     
      Z1=((HTBMEF*(TBULK(J)-TFZX(J)))/SIGOX(J))**2
      Z2=DCROLD(J)**2+(TKEFF*(TFZX(J)-TFZC(J)))/SIGOX(J)      
      GAMOX=SQRT(Z1+4.D0*Z2)    
      Z3=((TKEFF*(TFZX(J)-TFZC(J)))/(DCRUST(J)*SIGCON(J)))**2 
      Z4=ZABOLD(J)**2+(BATEVL*(TFZC(J)-TEMP(2,J)))/SIGCON(J)  
      GAM=SQRT(Z3+4.D0*Z4)      
      WJP1=-BATEVL/(GAM*SIGCON(J))
      Z5=(TKEFF*(TFZX(J)-TFZC(J)))/(SIGCON(J)*DCRUST(J))      
      Z6=(Z5*(1.D0-Z5/GAM))/(2.D0*DCRUST(J))
      Z7=(HTBMEF*(TBULK(J)-TFZX(J)))/(GAM*SIGOX(J))
      WBLKCR=-(HTBMEF*(1.D0-Z7))/(2.D0*SIGOX(J)) 
      WBLK=Z6*WBLKCR  
      ZX1=TKEFF/(2.D0*DTIME*SIGOX(J))     
      ZX2=HTBMEF/(2.D0*DTIME*SIGOX(J)) 
      FBLKCR=-(ZX1*(TFZX(J)-TFZC(J))*WBLKCR)/DCRUST(J)**2-ZX2 
      ZX1A=BATEVL/(2.D0*DTIME*SIGCON(J))  
      ZX2A=TKEFF/(2.D0*DTIME*SIGCON(J))   
      FBLKG=(ZX2A*(TFZX(J)-TFZC(J))*WBLKCR)/DCRUST(J)**2      
      FBLK=0.D0
      FJP1G=-(ZX1A*(TFZC(J)-TEMP(2,J))*WJP1)/ZABLAT(J)**2-ZX1A/ZABLAT(J)
      FJP1=0.D0
      DCDOT(J)=ZX1*(TFZX(J)-TFZC(J))/DCRUST(J)-ZX2*(TBULK(J)-TFZX(J))   
      DADOTG(J)=(ZX1A*(TFZC(J)-TEMP(2,J)))/ZABLAT(J)-(ZX2A*(TFZX(J)-TFZC
     1(J)))/DCRUST(J) 
      DADOT(J)=0.D0   
      BS0=0.D0
      AS1=FBLKCR*ALPBLK
      BS1=0.D0
      BT0=0.D0
      AT1=0.D0
      BT1=0.D0
      GO TO 101
   99 CONTINUE
      Z1=((HTBMEF*(TBULK(J)-TFZX(J)))/SIGCON(J))**2
      Z2=ZABOLD(J)**2+(BATEVL*(TFZC(J)-TEMP(2,J)))/SIGCON(J)  
      GAM=SQRT(Z1+4.D0*Z2)      
      WJP1=-BATEVL/(SIGCON(J)*GAM)
      WBLK=0.5D0*(((TBULK(J)-TFZX(J))*HTBMEF**2)/(GAM*SIGCON(J)**2)  
     1-HTBMEF/SIGCON(J))     
      ZX1=BATEVL/(2.D0*DTIME*SIGCON(J))   
      ZX2=HTBMEF/(2.D0*DTIME*SIGCON(J))
      DADOTG(J)=(ZX1*(TFZC(J)-TEMP(2,J)))/ZABLAT(J)-ZX2*(TBULK(J)-TFZX(J
     1))    
      DADOT(J)=0.D0   
      DCDOT(J)=0.D0   
      FBLKG=-(ZX1*(TFZC(J)-TEMP(2,J))*WBLK)/ZABLAT(J)**2-ZX2  
      FBLK=0.D0
      FJP1G=-(ZX1*(TFZC(J)-TEMP(2,J))*WJP1)/ZABLAT(J)**2-ZX1/ZABLAT(J)  
      BS0=0.D0
      AS1=0.D0
      BS1=0.D0
      BT0=0.D0
      AT1=0.D0
      BT1=0.D0
  101 CONTINUE
C.....CALCULATE MATRIX ELEMENTS FOR SECOND NODE WHEN SUBSTRATE IS
C.....ABLATING.
      CON12=BATEVL/ZABLAT(J)    
      DTDE3=DTDEB(3,J)
      TK3=FKB(3,J)    
      TKJP1=TK3
      ALPJP1=DTDE3    
      CON23=(TK2*TK3)/(TK2*(XDIST(2,J)-XBTW(2,J))+TK3*XBTW(2,J))
      TEM12=TFZC(J)-TEMP(2,J)   
      TEM23=TEMP(2,J)-TEMP(3,J) 
      DENP=ENTHP(2,J)-EOLD(2,J) 
      VOLUME=XBTW(2,J)
      A(2)=(VOLUME*DEN2*DENP)/DTIME-CON12*TEM12+CON23*TEM23-SDECAY      
      B(2)=(VOLUME*DEN2)/DTIME+DTDE2*(CON12+CON23+(TEM12*BATEVL*WJP1)/ZA
     1BLAT(J)**2)     
      C(2)=(TEM12*BATEVL*WBLK*ALPBLK)/ZABLAT(J)**2  
      D(2)=CON23*DTDE3
  100 CONTINUE
C.....CALCULATE MATRIX ELEMENTS, EXCEPT THOSE FOR THE ADIABATIC NODE,   
C.....IN THE INTERIOR OF THE SUBSTRATE REGION.      
      NUP=NODES(J)-1  
      DO 147 IDR=NDRIVE,NUP     
      DENSJ=DENB(IDR,J)
      VOLJ=XDIST(IDR-1,J)-XBTW(IDR-1,J)+XBTW(IDR,J) 
      ALPJM1=ALPJ     
      TKJM1=TKJ
      ALPJ=ALPJP1     
      TKJ=TKJP1
      IF(NTYPMT(IDR,J).GT.3) GO TO 201    
      SDECAY=0.D0     
      GO TO 2021      
  201 CONTINUE
      SDECAY=ROM(21)*QDCU*HBMT(IDR,J,6)+ROM(26)*QDCUO2*HBMT(IDR,J,15)   
 2021 CONTINUE
      IP=IDR+1
      ALPJP1=DTDEB(IP,J)
      TKJP1=FKB(IP,J) 
      CJM1=(TKJ*TKJM1)/(TKJ*XBTW(IDR-1,J)+TKJM1*(XDIST(IDR-1,J)-XBTW(IDR
     1-1,J)))
      CJP1=(TKJ*TKJP1)/(TKJP1*XBTW(IDR,J)+TKJ*(XDIST(IDR,J)-XBTW(IDR,J))
     1)     
      A(IDR)=(VOLJ*DENSJ*(ENTHP(IDR,J)-EOLD(IDR,J)))/DTIME-CJM1*(TEMP(ID
     1R-1,J)-TEMP(IDR,J))+CJP1*(TEMP(IDR,J)-TEMP(IDR+1,J))-SDECAY
      B(IDR)=(VOLJ*DENSJ)/DTIME+(CJM1+CJP1)*ALPJ    
      C(IDR)=-CJM1*ALPJM1
      D(IDR)=CJP1*ALPJP1
  147 CONTINUE
C.....CALCULATE MATRIX ELEMENTS FOR ADIABATIC NODES.
      NTOP=NODES(J)   
      DENS=DENB(NTOP,J)
      VOLB=XDIST(NUP,J)-XBTW(NUP,J)
      IF(NTYPMT(NTOP,J).GT.3) GO TO 2081  
      SDECAY=0.D0     
      GO TO 209
 2081 CONTINUE
      SDECAY=ROM(21)*QDCU*HBMT(NTOP,J,6)+ROM(26)*QDCUO2*HBMT(NTOP,J,15) 
  209 CONTINUE
      DENT=ENTHP(NTOP,J)-EOLD(NTOP,J)     
      DTEMP=TEMP(NTOP-1,J)-TEMP(NTOP,J)   
      A(NTOP)=(VOLB*DENT*DENS)/DTIME-CJP1*DTEMP     
      B(NTOP)=(VOLB*DENS)/DTIME+CJP1*ALPJP1
      C(NTOP)=-CJP1*ALPJ
      D(NTOP)=0.D0    
C.....GIVEN THE TDMA ELEMENTS IN THE J-TH SUBSTRATE VECTOR, SOLVE
C.....FOR THE FORWARD ELIMINATION COEFFICIENTS USING THE TDMA ALGORITHM.
      DO 151 IDR=1,NDRIVE-1     
      P(IDR)=D(IDR)/B(IDR)      
      Q(IDR)=-A(IDR)/B(IDR)     
  151 CONTINUE
      DO 152 IDR=NDRIVE,NODES(J)
      P(IDR)=D(IDR)/(B(IDR)+C(IDR)*P(IDR-1))
      Q(IDR)=-(A(IDR)+C(IDR)*Q(IDR-1))/(B(IDR)+C(IDR)*P(IDR-1))
  152 CONTINUE
C.....DO BACKWARDS SUBSTITUTION TO FIND THETO COEFFICIENTS.   
      THETO(NODES(J),J)=Q(NODES(J))
      DO 153 IDR=1,NODES(J)-1   
      IARG=NODES(J)-IDR
      THETO(IARG,J)=P(IARG)*THETO(IARG+1,J)+Q(IARG) 
  153 CONTINUE
C.....FIND THE THET1 COEFFICIENTS, EXCEPT WHEN THERE IS NO MELT PRESENT 
C.....AT THE MELT/BASEMAT INTERFACE.      
      IF(HTMP(J).GT.0.D0) GO TO 9010      
      DO 9011 IDR=1,NODES(J)    
      THET1(IDR,J)=0.D0
 9011 CONTINUE
      GO TO 9012      
 9010 CONTINUE
      DO 156 IDR=1,NDRIVE-1     
      Q(IDR)=-C(IDR)/B(IDR)     
  156 CONTINUE
      DO 157 IDR=NDRIVE,NODES(J)
      Q(IDR)=-(C(IDR)*Q(IDR-1))/(B(IDR)+C(IDR)*P(IDR-1))      
  157 CONTINUE
C.....DO BACKWARDS SUBSTITUTION TO FIND THET1 COEFFICIENTS.   
      THET1(NODES(J),J)=Q(NODES(J))
      DO 158 IDR=1,NODES(J)-1   
      IARG=NODES(J)-IDR
      THET1(IARG,J)=P(IARG)*THET1(IARG+1,J)+Q(IARG) 
  158 CONTINUE
 9012 CONTINUE
C.....WITH THET COEFFICIENTS DETERMINED, FIND CRUSTING & ABLATION
C.....FUNCTIONS FOR SOLUTION OF CONSERVATION OF MASS & ENERGY EQUATIONS.
      SIG0(J)=BS0*THETO(1,J)    
      SIG1(J)=AS1+BS1*THET1(1,J)
      TAO0(J)=BT0*THETO(2,J)    
      TAO1(J)=AT1+BT1*THET1(2,J)
C...................................................................... 
C.....NOW EVALUATE THE UNBOUND/BOUND WATER & CO2 GAS VELOCITY DERIVATIVE
C..... FUNCTIONS FOR SOLUTION OF CONERVATION OF MASS AND ENERGY EQS.
      DO 252 IOUT=1,4 
      IF(NPASSG(J).EQ.1) GO TO 299
      IF(HTMP(J).LE.0.D0) GO TO 299
      GO TO(253,254,255,256),IOUT
  253 CONTINUE
      TCOMP=TFWL      
      BDCP=XFH2OU     
      GO TO 257
  254 CONTINUE
      TCOMP=TBWL      
      BDCP=(XFCAOH*XMH2O)/XMCAOH
      GO TO 257
  255 CONTINUE
      TCOMP=TMCAL     
      BDCP=(2.D0*XFMGCA*XMCO2)/XMMGCA     
      GO TO 257
  256 CONTINUE
      TCOMP=TCAL      
      BDCP=(XFCACO*XMCO2)/XMCACO
  257 CONTINUE
      IF(BDCP.LE.0.D0) GO TO 299
C.....FIRST CHECK IF IOUT-TH ISOTHERM LIES BETWEEN THE IDR & IDR+1      
C.....NODES.
      DO 237 IDR=1,NODES(J)-1   
      SIGN=(TEMP(IDR,J)-TCOMP)*(TEMP(IDR+1,J)-TCOMP)
      IF(SIGN.GT.0.D0) GO TO 237
      IF(TEMP(IDR+1,J).EQ.TEMP(IDR,J)) GO TO 237    
C.....ALGORITHM REACHES HERE, THEN ISOTHERM HAS BEEN FOUND.   
      IF(IDR.GT.1) GO TO 243    
      IF(NBCINT(J).LE.3) GO TO 243
C.....THE FOLLOWING FINDS THE GAS MASS FLUX WHEN ISOTHERM LIES ADJACENT 
C.....TO AN ABLATING BOUNDARY NODE.
      IF(NUMOLD(IOUT,J).GT.IDR) GO TO 237 
      DXSAT=ZABLAT(J)*((TCOMP-TEMP(IDR,J))/(TEMP(IDR+1,J)-TEMP(IDR,J))) 
      XLEN=XDISTO(J)-ZABLAT(J)+DXSAT      
      IF(XLEN.GE.XBTWO(J)) GO TO 248      
      IP=IDR
      GO TO 273
  248 CONTINUE
      IP=IDR+1
  273 CONTINUE
      NPROP=NTYPMT(IP,J)
C.....CHECK TO SEE IF ISOTHERM LIES IN GAS PRODUCING REGION.  
      IF(NPROP.GT.3) GO TO 237  
      IF(NL(IP,J).EQ.2) GO TO 237
      I2=IDR+1
      BDCK=ROC*BDCP   
      XDOTG=SMFLX(IOUT,J)/BDCK  
      VL2=XBTW(I2,J)  
      IF(NTYPMT(I2,J).GT.3) GO TO 1232    
      SDECAY=0.D0     
      GO TO 1233      
 1232 CONTINUE
      SDECAY=ROM(21)*QDCU*HBMT(I2,J,6)+ROM(26)*QDCUO2*HBMT(I2,J,15)     
 1233 CONTINUE
      EDOTG=(BET(J)*TEM12/ZABLAT(J)-CON23*TEM23+SDECAY)/(DEN2*VL2)      
      Z1=XDOTG*DTDE2/TEM12      
      Z2=(DTDE2*(DADOTG(J)+(ZABLAT(J)*DTDE2*EDOTG*(TFZC(J)-TCOMP))/(TEM1
     12*TEM12)))/TEM12
      Z3=(TFZC(J)-TCOMP)/TEM12**2
      Z4=((ZABLAT(J)*DTDE2*DTDE2*Z3)/(DEN2*VL2*TEM12))*(BET(J)/ZABLAT(J)
     1+CON23)
      Z5=EDOTG-(BET(J)*TEM12)/(ZABLAT(J)*DEN2*VL2)  
      Z6=(DTDE2*DTDE2*WJP1*Z3*Z5)/TEM12   
      Z7=((TCOMP-TEMP(2,J))*FJP1G*DTDE2)/TEM12      
      ZET2=Z1+Z2-Z4+Z6-Z7
      ZET3=(ZABLAT(J)*DTDE2*DTDE3*Z3*CON23)/(TEM12*DEN2*VL2)  
      ZETBLK=(DTDE2*Z3*Z5*ALPBLK*WBLK)/TEM12-((TCOMP-TEMP(2,J))*ALPBLK*F
     1BLKG)/TEM12     
      OM0=ZET2*THETO(IDR+1,J)+ZET3*THETO(IDR+2,J)   
      OM1=ZET2*THET1(IDR+1,J)+ZET3*THET1(IDR+2,J)+ZETBLK      
      OMEG0(IOUT,J)=OM0*BDCK    
      OMEG1(IOUT,J)=OM1*BDCK    
      GO TO 252
  243 CONTINUE
C.....DETERMINE IF GAS IS GENERATED IN NON-BOUNDARY AND/OR NON ABLATING 
C.....NODES.
      DXSAT=XDIST(IDR,J)*((TCOMP-TEMP(IDR,J))/(TEMP(IDR+1,J)-TEMP(IDR,J)
     1))    
      IF(DXSAT.GE.XBTW(IDR,J)) GO TO 228  
      IP=IDR
      GO TO 229
  228 CONTINUE
      IP=IDR+1
  229 CONTINUE
      NPROP=NTYPMT(IP,J)
      IF(NPROP.GT.3) GO TO 237  
      IF(NL(IP,J).EQ.2) GO TO 237
      IF(IDR.LT.NUMOLD(IOUT,J)) GO TO 237 
C.....SET CONSTANTS REQUIRED FOR THE EVALUATION OF THE DEGASSING
C.....FORWARD ELIMINATION COEFFICIENTS.   
      LM1=IDR-1
      L=IDR 
      LP1=IDR+1
      LP2=IDR+2
      DENGJ=DENB(L,J) 
      DENGK=DENB(LP1,J)
      BDCK=ROC*BDCP   
      XDOTG=SMFLX(IOUT,J)/BDCK  
C.....SET INTERNODAL CONDUCTANCES, VOLUMES, AND LENGTHS.      
      VLGJ=XBTWO(L)   
      IF(L.GT.1) VLGJ=XDIST(LM1,J)-XBTW(LM1,J)+XBTW(L,J)      
      VLGJP1=XDIST(L,J)-XBTW(L,J)+XBTW(LP1,J)
      XLJJP1=XDIST(L,J)
      XLFT=XBTW(L,J)/XLJJP1     
      XRFT=1.D0-XLFT  
      CJP12=(FKB(L,J)*FKB(LP1,J))/(FKB(LP1,J)*XBTW(L,J)+FKB(L,J)*(XDIST(
     1L,J)-XBTW(L,J)))
      DJM12=CJP12     
      DENOM=FKB(LP2,J)*XBTW(LP1,J)+FKB(LP1,J)*(XDIST(LP1,J)-XBTW(LP1,J))
      DJP12=0.D0      
      IF(DENOM.GT.0.D0) DJP12=(FKB(LP1,J)*FKB(LP2,J))/DENOM   
      IF(L.GT.1) GO TO 3031     
      GAMCD=HTBMEF*(TARGB(J)-TEMP(1,J))
      IF(NBCINT(J).EQ.2) GAMCD=(TKX(J)*(TFZX(J)-TEMP(1,J)))/DCRUST(J)  
      IF(NBCINT(J).EQ.3) GAMCD=HTBMEF*(TBULK(J)-TFZX(J))   
      GO TO 3032      
 3031 CONTINUE
      IF(L.GT.2.OR.NBCINT(J).LE.3) GO TO 3033
      GAMCD=(BET(J)*(TFZC(J)-TEMP(2,J)))/ZABLAT(J)  
      GO TO 3032      
 3033 CONTINUE
      CJM12=(FKB(LM1,J)*FKB(L,J))/(FKB(L,J)*XBTW(LM1,J)+FKB(LM1,J)*(XDIS
     1T(LM1,J)-XBTW(LM1,J)))    
      GAMCD=CJM12*(TEMP(LM1,J)-TEMP(L,J)) 
 3032 CONTINUE
      IF(NTYPMT(L,J).GT.3) GO TO 4032     
      SDECAJ=0.D0     
      GO TO 4033      
 4032 CONTINUE
      SDECAJ=ROM(21)*QDCU*HBMT(L,J,6)+ROM(21)*QDCUO2*HBMT(L,J,15)
 4033 CONTINUE
      IF(NTYPMT(LP1,J).GT.3) GO TO 4034   
      SDECAK=0.D0     
      GO TO 4035      
 4034 CONTINUE
      SDECAK=ROM(21)*QDCU*HBMT(LP1,J,6)+ROM(21)*QDCUO2*HBMT(LP1,J,15)   
 4035 CONTINUE
      EDOTJ=(GAMCD-CJP12*(TEMP(L,J)-TEMP(LP1,J))+SDECAJ)/(DENGJ*VLGJ)   
      EDOTK=(DJM12*(TEMP(L,J)-TEMP(LP1,J))-DJP12*(TEMP(LP1,J)-TEMP(LP2,J
     1))+SDECAK)/(DENGK*VLGJP1) 
      IF(L.GT.1) GO TO 4045     
      BETKK=HTBMEF 
      IF(NBCINT(J).EQ.2) BETKK=TKX(J)/DCRUST(J)    
      IF(NBCINT(J).EQ.3) BETKK=0.D0
      GO TO 4046      
 4045 CONTINUE
      BETKK=CJM12     
      IF(J.EQ.2.AND.NBCINT(J).GT.3) BETKK=BET(J)/ZABLAT(J)    
 4046 CONTINUE
      C1=2.D0*XDOTG+(XRFT*XLJJP1*DTDEB(LP1,J)*EDOTK)/(TEMP(LP1,J)-TEMP(L
     1,J))  
      C2=(DTDEB(L,J)*C1)/(TEMP(LP1,J)-TEMP(L,J))    
      C3=(XLFT*XLJJP1*DTDEB(L,J)*DTDEB(L,J)*(TCOMP-TEMP(LP1,J))*(BETKK+C
     1JP12))/(DENGJ*VLGJ*(TEMP(LP1,J)-TEMP(L,J))**2)
      C4=(XRFT*XLJJP1*DTDEB(L,J)*DTDEB(LP1,J)*(TEMP(L,J)-TCOMP)*DJM12)/(
     1DENGK*VLGJP1*(TEMP(LP1,J)-TEMP(L,J))**2)      
      ZETJ=C2-C3+C4   
      C1=2.D0*XDOTG+(XLFT*XLJJP1*DTDEB(L,J)*EDOTJ)/(TEMP(LP1,J)-TEMP(L,J
     1))    
      C2=(DTDEB(LP1,J)*C1)/(TEMP(LP1,J)-TEMP(L,J))  
      C3=(XLFT*XLJJP1*DTDEB(L,J)*DTDEB(LP1,J)*(TCOMP-TEMP(LP1,J))*CJP12)
     1/(DENGJ*VLGJ*(TEMP(LP1,J)-TEMP(L,J))**2)      
      C4=(XRFT*XLJJP1*DTDEB(LP1,J)*DTDEB(LP1,J)*(TEMP(L,J)-TCOMP)*(DJM12
     1+DJP12))/(DENGK*VLGJP1*(TEMP(LP1,J)-TEMP(L,J))**2)      
      ZETJP1=-C2+C3-C4
      ZETJP2=(XLJJP1*DTDEB(LP1,J)*DTDEB(LP2,J)*(TEMP(L,J)-TCOMP)*DJP12)/
     1(VLGJP1*DENGK*(TEMP(LP1,J)-TEMP(L,J))**2)     
      ZETJM1=0.D0     
      IF(L.EQ.1) GO TO 1511     
      C1=(XLJJP1*DTDEB(L,J)*DTDEB(LM1,J)*(TCOMP-TEMP(LP1,J))*CJM12)/(DEN
     1GJ*VLGJ*(TEMP(LP1,J)-TEMP(L,J))**2) 
      IF(L.GE.2.AND.NBCINT(J).LE.3) ZETJM1=C1
      IF(L.GE.3) ZETJM1=C1      
 1511 CONTINUE
      C1=-(XLJJP1*DTDEB(L,J)*DTDEB(L,J)*(TCOMP-TEMP(LP1,J)))/(DENGJ*VLGJ
     1*(TEMP(LP1,J)-TEMP(L,J))**2)
      ZETG=0.D0
      IF(NBCINT(J).EQ.2.AND.L.EQ.1) ZETG=(C1*TKX(J)*(TFZX(J)-TEMP(L,J))*
     1WJP1)/DCRUST(J)**2
      IF(NBCINT(J).GT.3.AND.L.EQ.2) ZETG=(C1*BET(J)*(TFZC(J)-TEMP(L,J))
     1*WJP1)/ZABLAT(J)**2
      ZETB=0.D0
      C1=(XLJJP1*DTDEB(L,J)*(TCOMP-TEMP(LP1,J))*ALPBLK)/(DENGJ*VLGJ*(TEM
     1P(LP1,J)-TEMP(L,J))**2)   
      IF(L.GT.1) GO TO 1803     
      ZETB=C1*HTBMEF
      IF(NBCINT(J).EQ.2) ZETB=-(C1*TKX(J)*(TFZX(J)-TEMP(L,J))*WBLK)/DCR
     1UST(J)**2
      GO TO 1805      
 1803 CONTINUE
      IF(L.GT.2) GO TO 1805    
      IF(NBCINT(J).GT.3) ZETB=-(C1*BET(J)*(TFZC(J)-TEMP(L,J))*WBLK)/ZABL
     1AT(J)**2
 1805 CONTINUE
      OM0=(ZETJ+ZETG)*THETO(L,J)+ZETJP1*THETO(LP1,J)+ZETJP2*THETO(LP2,J)
      IF(L.GE.2) OM0=OM0+ZETJM1*THETO(LM1,J)
      OM1=(ZETJ+ZETG)*THET1(L,J)+ZETJP1*THET1(LP1,J)+ZETJP2*THET1(LP2,J)
     1+ZETB 
      IF(L.GE.2) OM1=OM1+ZETJM1*THET1(LM1,J)
      OMEG0(IOUT,J)=OM0*BDCK    
      OMEG1(IOUT,J)=OM1*BDCK    
      GO TO 252
  237 CONTINUE
  299 CONTINUE
      OMEG0(IOUT,J)=0.D0
      OMEG1(IOUT,J)=0.D0
  252 CONTINUE
   85 CONTINUE
      RETURN
      END