C...................................................................... 
C.....GIVEN THE SPECIFIC ENTHALPY OF WATER AND THE DRYWELL PRESSURE,
C.....SUBROUTINE EWTEMP CALCULATES THE TEMPERATURE AND THE DERIVATIVE
C.....OF THE TEMPERATURE WITH RESPECT TO ENTHALPY.  TEMPERATURE CHANGE
C.....GOING FROM SATURATED LIQUID TO SATURATED VAPOR IS ASSUMED 
C.....TO BE 1 C.
C...................................................................... 
      SUBROUTINE EWTEMP(E,T,P,DTDE)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      REAL(8) KL
      DATA TREF /273.15D0/
      CALL CONWAT(TSAT,KL,PL,CL,UL,HLV,EWL,EWV,CWV,SIGMA,P)
      IF(E.GE.EWL) GO TO 10
      T=TREF+E/CL
      DTDE=1.0D0/CL
      GO TO 30
   10 CONTINUE
      IF(E.GT.EWV) GO TO 20
      T=TSAT+(E-EWL)/HLV
      DTDE=1.D0/HLV
      GO TO 30
   20 CONTINUE
      T=TSAT+1.D0+(E-EWV)/CWV
      DTDE=1.D0/CWV
   30 CONTINUE
      RETURN
      END