C.......................................................................
C
C                Copyright (C) 2018, UChicago Argonne, LLC
C                         All Rights Reserved
C                     Software Name: MELTSPREAD3.0
C                   By: Argonne National Laboratory
C                         OPEN SOURCE LICENSE
C
C  Redistribution and use in source and binary forms, with or without 
C  modification, are permitted provided that the following conditions
C  are met:
C
C  1. Redistributions of source code must retain the above copyright 
C     notice, this list of conditions and the following disclaimer.
C  2. Redistributions in binary form must reproduce the above copyright 
C     notice, this list of conditions and the following disclaimer in 
C     the documentation and/or other materials provided with the 
C     distribution.
C  3. Neither the name of the copyright holder nor the names of its 
C     contributors may be used to endorse or promote products derived
C     from this software without specific prior written permission.
C
C***********************************************************************
C
C                             DISCLAIMER
C
C  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
C  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
C  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
C  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
C  COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
C  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
C  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
C  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
C  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
C  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
C  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
C  POSSIBILITY OF SUCH DAMAGE.
C 
C***********************************************************************
C..... MELTSPREAD SOLVES THE COUPLED MASS, MOMENTUM, AND ENERGY 
C..... EQUATIONS DESCRIBING THE MOTION OF MOLTEN CORIUM OVER A 
C..... BASEMAT WITH ARBITRARILY SPECIFIED ELEVATION.  THE CODE 
C..... CAN COMPUTE LOCAL CRUSTING, ABLATION, OR SIMULTANEOUS
C..... CRUSTING AND ABLATION AT THE MELT/BASEMAT INTERFACE, DEPENDING    
C..... ON THE THERMAL CONDITIONS AT THIS INTERFACE.  THE CODE
C..... TRACKS THE PROPAGATION OF UP TO 15 MELT CONSTITUENTS 
C..... ARE TYPICALLY PREDICTED TO BE RELEASED FROM THE RPV USING 
C..... SYSTEM LEVEL SEVERE ACCIDENT CODES SUCH AS MAAP AND MELCOR.  
C
C..... THIS CODE WAS DEVELOPED AT ARGONNE NATIONAL LABORATORY BY
C..... MITCH FARMER AND HAS UNDERGONE SEVERAL REVISONS AND UPDATES
C..... OVER THE COURSE OF ITS LIFETIME THAT ARE SUMMARIZED BELOW.  
C...................................................................... 
C$$$$$ THIS VERSION OF MELTSPREAD, VERSION 1.03, WAS GENERATED ON 
C$$$$$ 1-8-96 BY MTF.  IT INCLUDES THREE ERROR CORRECTIONS, SUMMARIZED
C$$$$$ AS FOLLOWS: (i) ZrO2 LIQUID/SOLID PHASE DENSITIES SWITCHED IN 
C$$$$$ SUBROUTINE CPROPI, (ii) SUBROUTINE TEF (MELT  ENTHALPY --> 
C$$$$$ TEMPERATURE) ROUTINE CORRECTED, AND (iii) SUBROUTINE ETF(TEMP.
C$$$$$ -->ENTHALPY) CORRECTED.
C...................................................................... 
C##### THIS VERSION OF MELTSPREAD, 1.04, WAS GENERATED ON 1-18-06 BY MTF.
C##### IT FIXED A FEW BUGS, WHICH INCLUDED A MISS-DIRECTED DO LOOP 
C##### (SEARCH ON STRING 638) AND TWO INCOMPATIBLE SUBROUTINE ARGUMENTS 
C##### THAT CAUSED SEGMENTATION FAULTS.  (LINE NOS. 326 AND 968).  THESE 
C##### CAUSED RUN ERRORS USING CIRCA 2006 COMPILERS.
C...................................................................... 
C$$$$$ THIS VERSION OF MELTSPREAD, 2.0, WAS DEVELOPED UNDER NRC
C$$$$$ SPONSORSHIP.  THIS VERSION INCORPORATED UPGRADES THAT INCLUDED
C$$$$$ A NEW MELT VISCOSITY MODEL AS WELL AS THE ABILITY TO READ IN 
C$$$$$ THERMOPHYSICAL PROPERTIES FOR NON-NUCLEAR MELT AND SUBSTRATE 
C$$$$$ MATERIALS.  THE ABILITY TO DO ADIABATIC SPREADING ANALYSIS WAS
C$$$$$ ALSO ADDED.  FINALLY AN EXTENSIVE CODE VALIDATION CAMPAIGN WAS
C$$$$$ CONDUCTED IN WHICH THE CODE WAS VALIDATED AGAINST 35 DIFFFERENT 
C$$$$$ EXPERIMENTS AND ANALYTICAL CASES.  THIS WORK WAS COMPLETED IN 
C$$$$$ 2/16/2008 AND DOCUMENTED IN THE ANL REPORT ANL-09-10.  IN THE 
C$$$$$ ARCHIVE MELTSPREAD DEVELOPMENT DIRECTORY, THIS CORRESPONDS TO
C$$$$$ VERSION test28.f.
C...................................................................... 
C##### VERSIONS TEST28.F TO TEST32.F ARE THE VARIOUS WORKING VERSIONS 
C##### OF MELTPSREAD THAT WERE DEVELOPED AS PART OF THE DOE-SPONSORED
C##### ANALYSES THAT ENDED IN 2012.  VERSION TEST34.F IS THE FINAL 
C##### VERSION DEVELOPED AS PART OF THAT WORK AND WAS USED IN ALL 
C##### CALCULATIONS CARRIED OUT AS PART OF THAT WORK.  THE RESULTS ARE 
C##### ORNL/TM-012/455.  RELATIVE TO VERSION TEST28.F, THIS VERSION HAD 
C##### ADDITIONAL I/O ADDED TO SUPPORT THE ORNL CQ WORK, AND ALSO HAD 
C##### UPDATED WATER PROPERTY SUBROUTINES TO REFLECT THE FACT THAT THOSE
C##### CONTAINMENTS WENT WELL ABOVE 4 BAR, THE ORIGINAL WATER SUBROUTINE 
C##### LIMITS.  THIS WAS ALSO THE VERSION USED FOR THE EPRI ANALYSIS TO
C##### TO SUPPORT FAI IN THE MAAP UPGRADE PROJECT.
C...................................................................... 
C$$$$$ THIS VERSION OF MELTSPREAD, 3.0, WAS DEVELOPED UNDER DOE SUPPORT
C$$$$$ AS PART OF THE WORK TO SUPPORT INDUSTRY IN BWR SEVERE ACCIDENT
C$$$$$ WATER MANAGEMENT (SAWM) WORK.  MAJOR UPGRADES INCLUDED THE   
C$$$$$ ADDITION OF A MELT JET BREAKUP MODEL AS THE CORE DEBRIS RELOCATES
C$$$$$ THROUGH WATER FROM THE RPV TO THE FLOOR, A DETAILED WATER 
C$$$$$ INVENTORY MODEL THAT ALLOWS FOR FLOW OVER EXISTING CORE DEBRIS
C$$$$$ ON THE FLOOR, INJECTION FROM ARBITRAY POINTS, AND A WATER SPILL
C$$$$$ OVER MODEL INTO TORUS REGION.  THE CODE WAS ALSO RESTRUCTURED
C$$$$$ INTO SUBROUTINES AS OPPOSED TO A MAJOR BLOCK PROGRAMMING 
C$$$$$ APPROACH
C...................................................................... 
      PROGRAM MELTSPREAD3
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON /LABEL/ TITLE(72)
      COMMON /WATVARS/FCRUST(999),VLW(999),VLWOLD(999),DWAT(999),
     1DWATOLD(999),EWAT(999),EWATOLD(999),TWAT(999),CORDDC(999),
     2DSRDC(999),DHDC(999),TSRDC,TINTDC,HWATB(999),TSURFW(999),XMS(999),
     3XMST,XINTS,ESRDTW(999),TSRDTW(999),DSRDTW(999),TSRDW,TINTDW,
     4TWATI,ELDCO(999),ELDCX(999,99),CRDCX(999,99),TIMINJ(999,99),
     5XDTINJ(999,99),TDTINJ(999,99),ELWATI,XMWAT,XMWATO,XBALW,
     6HDRY(999),EINTW,XMCT(199),XMCDT(16,999),TMPCDT(999),CMPCDT(999),
     7FDC(999),FCOV(999),FBED(999),FHEAT(999),XFACJ(999),
     8XMBEDJ(16,999),XMBEDJT(999),PBED,QBED(999),QWATER(999),
     9QSURFACE(999),QWATERT(999),HBED(999),POROSBED,XMCRDT(16,999),
     1XMCRT(999),XMBDINT(999),XMT(999)
      COMMON /WATINT/NDOWNC,NDC(999),NPTDC(999),NINJ,NINJP(999),
     1NPTINJ(999)
      COMMON/CATCHR/A(999),B(999),C(999),D(999),P(999),Q(999),
     1RECON(999),DELVEL(999),DSRDT(999),DELHTS(999),EMAX(999,999),
     2DBLKEN(999),DELHIT(16,999),SOURCE(16,999),SRCTOT(999),
     3HCROLD(16,999),DCDOT(999),HCRUST(16,999),DFILM(16,999),
     4DFMOLD(16,999),DENOLD(999),SIGOX(999),SIGCON(999),BET(999),
     5TFZX(999),TFZC(999),TKX(999),TKM(999),THETO(999,999),
     6THET1(999,999),OMEG0(4,999),OMEG1(4,999),TAO0(999),TAO1(999),
     7SIG0(999),SIG1(999),TARGB(999),DADOT(999),DADOTG(999),
     8XLOLD(4,999),VISREX(999),TATMS(999),HTMP(999),DHTMP(999),
     9HTMOLD(999)
      COMMON/CATCHI/NUMS(4,999),NUMOLD(4,999),NTRACK(16),NSUMP(999),
     1NPASSG(999),NCRSTM(999),NCRRT(999),NPASS(999),NBURN,NBURNO     
      COMMON/PRINTB/ELEVAT(999),ELOLD(999),XDIST(999,999),XBTW(999,999),
     1TEMP(999,999),ENTHP(999,999),EOLD(999,999),ENBLK(999),EBKOLD(999),
     2TBULK(999),HITE(16,999),HITOLD(16,999),HTOT(999),HTOLD(999),
     3HTCFT(999),HTCOEF(999),QFLUXT(999),QFLUXB(999),VEL(999),ELO(999),
     4VELOLD(999),SRSCOR(16),AREA(999),RAD(999),ARC(999),VOLCN(16),
     5VOID(999),VGJ(999),ZABLAT(999),ZABOLD(999),DCRUST(999),
     6DCROLD(999),DABCON(999),DABOLD(999),DFILMT(999),DFOLT(999),
     7SMFLX(4,999),XLSMF(4,999),TOTVOL,XFACMS(999),XMFLXA,XMCORT,
     8VCORT,TOTOX,TOTMET,QFLXT,QFLXB,TIME,DTIME,XMCOR(16),VCOR(16),
     9TCONI,RSAND,HDOWNC,TBOUND,EMISCN,PDRYWL,XDISTO(999),QOXT(999),
     1XLENSH,XBTWO(999),RCOMP,WDOOR,RSUMP,RSHELL,RPED,TPED,ELSMP,
     1TENDP(10,999),TFRZSH,TDEBRS,TKDEBR,PDEBR,CPDEBR,ENENDP(10,999),
     2ENOLDP(10,999),DXVERT,DXSNK,XDSTE(10,999),XBTE(10,999),HXLA(999),
     3HXLB(999),TSFEB(999),DCRS(999),DCRSLD(999),HCRS(16,999),
     4HCRSLD(16,999),THETE0(10,999),THETE1(10,999),QSHELL,QSHELE,TSHELI,
     5SIGOXE(999),FKOXE(999),RINJC,XLSEC,ANGSEC,ANINJC,XLCHAN,WCHNL,
     6TEFZX(999),TIMSPC(999),DXNODE(999),TNORM(999),FRCSOL(999),
     7ALPSPR(999),CRAMCON,HINTF,TSHLMX,XFRMX(999),XFROX(999),XFRTX(999),
     8XMLMX(999),XMLOX(999),XMLTX(999),XTOTX(999),TIMEO,TMAX,EDOWN(999),
     9HCP(999)
      COMMON/HCONS/HMETAL(999),HOXIDE(999)  
      COMMON/PROPI/ NMATC,NMATFI,NMATFF,ICAOH2,ICACO3,IMCCO3,IFH2O,     
     1IVH2O,ICK2O,IVK2O,INA2O,ITIO2,ISIO2,ICAO,IMGO,IAL2O3,IFEO,IFE2O3, 
     2IFE3O4,IFE,ICR,INI,IZR,IU,IB4C,IB,ICR2O3,INIO,IUO2,IZRO2,IB2O3,   
     3NBCINT(999),NODES(999),NUMNOD,IMOX(28),IBAS,ILCS,ILL,NACTIV(999),     
     4NBFRZM,NBFRZO,NABLFM,NDRNFM,NTYPMT(999,999),NDOOR,NBMADJ,NUMSHV,   
     5NBSHL(999),NCRSTS(999),NUMSHH,NSKIPE,NACSH,NWAT,NPEND,NBCBOT,
     6NCRTOP,NBFZOE,NBFZME,NGEOM,NL(999,999),NFRSCT,NLOGSH,NADAB,NINVIS,
     7NSIMST,NSTEEL,NOVHT,NOVTK,NOVUM,NOVEM,NOVSIG,NPLLOC(999),NBPL,
     8IXP(999),IYP(999),NVTPE,NSOLTP,NSOLF,NINTF,IFLGA(999),ICTYPE,ICTC,
     9NPOURS,NSMP,NPED,NDOR,NSHL,NANULS,NSMPCV,NBOIL,NSWALL,NMVER,
     1NCRTEM,NTHINC,NVELP,NITMAX,NENMAX,NPRINT,NPFREQ,NTIMSPC,NPLFREQ,
     2NPLTOT,NJET,NJETP,NJETD,NJETND,NODCAP,NVELPW,NITMAXW,NENMXW,
     3IFLGJ(999),NBEDCQ,ISHELE
      COMMON/DATOVER/COVS,COVL,DHSOV,XMOLOV,ROVS,ROVL,TKOVS,TKOVL,VISOV,
     1EMOV,SIGOV
      COMMON/PRINTR/ QFEH2O,QCRH2O,QZRH2O,QFECO2,QCRCO2,QZRCO2,
     4XFH2OU,XFCAOH,XFMGCA,XFCACO,XZRMRE,XFEMRE,XCRMRE,XZRORE,XFEORE,   
     5XCRORE,XMH2O,XMCO2,XMCACO,XMMGCA,XMCAOH,TFWL,TFWS,TBWL,TBWS,      
     6TMCAL,TMCAS,TCAL,TCAS,TFOS,TFOL,TFMS,TFML,XVISC(28),SVISC(28),    
     7XMOL(28),FMMOL(28),ROM(28),ROMLIQ(28),AEQM(28,2),BEQM(28,2),
     8CEQM(28,2),ECL,ECS,ECAL,ECAS,EMCAL,EMCAS,EBWL,EBWS,EFWL,EFWS,    
     9STEF,GRAV,PI,TCS,TCL,CCL,CCS,RMASSL,WPCC,WPM,WPA,WPCS,ROC,RMASSS,   
     1ANGSHL,RSLAGL,RSLAGS,HNODT,VFAV,VGAV,QXAV,XWTSS(16),  
     2TSCS(2),TSCL(2),ESCS(2),ESCL(2),CCSS(2),CCSL(2),ROSTLS,ROSTLL,
     3XFRGAS,HMINC,TST(99),TSTOP(99),AINTP(99),BINTP(99),DRATIO(999),
     4XBCN(999),XDCN(999),XBLT(15),ADEC(99),BDEC(99),APOUR(16,99),
     5BPOUR(16,99),XWTC(14),BWIDTH,THCKCV,TMBOIL,TEBOIL,VFINT,ANGFAN,
     6ALPMAX,THSHL,XFCABL,XNDMIN,DVMX,DAVMX,DEAVMX,DEMX,TDC,QDCU,QDCUO2,
     7TSINJ,EINJ,DTINJ,TKINJ,ROEV,CPINJ,SURFT,VSINJ,EMINJ,TSINJO,EINJO,
     8DTINJO,TKINJO,ROEVO,CPINJO,SURFTO,VSINJO,EMINJO,XLEADE,ARSUM,
     9DBUBOX,UTRISE,TREMSH,DJET,DFALL,WEBER,FROUDE,XPSAITO,XPEPSTN,
     1FRAG,XMBEDT,XMBED(16),XLPENT,XLPENA,UJET,UFALL,HFALL,ERPV,
     2TJETT(99),DJETT(99),HWATP,XDOTJET,DVMXW,DAVMXW,DEMXW,DEAVMXW,
     3QJETW,XSTMJF,TINTSJF,ESAT,DRDOOR,DRANL,EI,QDCBUO2,QDCBU,
     4EBEDS,EBEDB
      COMMON/BLKHT/TKMLT,PM,CM,UM,EMISM,SIGMAM,TKNC,PNC,CNC,UNC    
      COMMON/BASPR/ HBMT(999,999,16),HBMOLD(999,999,16)
      COMMON/DATSH/TSTLS,TSTLL,ESTLS,ESTLL,DFUSST,CSTLL
      COMMON/DATSIMS/TSIS,TSIL,CSIS,CSIL,DHSIL,RSIS,RSIL,TKSIS,TKSIL,
     1ESIL,XCSI(16)
      COMMON/DEFUNC/CPLIQP,CPSOLP,EFOSP,EFOLP,EFMSP,EFMLP     
      COMMON/PROPB/CPBM(999),FKB(999,999),DENB(999,999),DTDEB(999,999),
     1EMIBM(999),DENCRS(999),ENCRS(999),FKRF(999),DENRF(999),CPRF(999) 
      COMMON/PROPM/DTDEM(999),CPMLT(999),FKMLT(999),DENMLT(999),
     1SIGMLT(999),UMMLT(999),EMIMLT(999)      
      OPEN(UNIT=2,FILE='diag.dat')
      OPEN(UNIT=5,FILE='spreadin.dat')
      OPEN(UNIT=6,FILE='spreadout.dat')
      OPEN(UNIT=31,FILE='meltloc.dat')
      WRITE(2,1) 
    1 FORMAT('Diagnostics file output:',/)
C.....HERE WE GO.  FIRST READ INPUT DATA....
      CALL READER
C.....GIVEN THE INPUT DATA, INITIALIZE THE NODALIZATIONS AND THERMAL-
C.....HYDRAULIC CONDITIONS
      CALL INITIAL
C...................................................................... 
C.....THE FOLLOWING SECTION OF CODE COVERS TIME STEPPING THROUGH 
C.....CALCULATION FROM TIME=TIMEO TO TMAX; LOOP ENDS AT '1719 CONTINUE'
      TIME=TIMEO      
      IFAILJ=0
      NROUND=0
      NPLRND=0
      IFINISH=0
 1700 CONTINUE
      IF(NPLFREQ.EQ.0) GO TO 4541 
      IF(NPLRND.LT.NPLFREQ) GO TO 4541
      NPLRND=0
 4541 CONTINUE
      IF(NROUND.LT.NPFREQ) GO TO 4542     
      NROUND=0
 4542 CONTINUE
      NROUND=NROUND+1 
      NPLRND=NPLRND+1
      IF(TIME.GT.TMAX) GO TO 1719
      TIME=TIME+DTIME 
      IF(TIME.GE.TMAX) IFINISH=1
C.....UPDATE THE MELT POUR SOURCE MASS POUR RATE, TEMPERATURE, AND
C.....DECAY HEAT AT THE CURRENT TIMESTEP.
      CALL MSOURCE(IFAILJ)
C.....IF DEBRIS FRAGMENTATION RENDERS CORE DEBRIS INTO SOLID STATE UPON
C.....IMPACT WITH FLOOR, TERMINATE RUN.
      IF(IFAILJ.EQ.1) GO TO 1719
C.....CHECK TO SEE IF NEW NODES HAVE BEEN COVERED BY MELT AND, IF SO, 
C.....ACTIVATE THE CALCULATION AT THOSE NODAL LOCATIONS
      CALL ACTIVATE     
C.....FOR CASES IN WHICH A SUMP COVER PLATE ANALYSIS IS PERFORMED, CHECK 
C.....TO SEE IF PLATE HAS FAILED AND, IF SO, RESET THE CALCULATION. 
      CALL SUMPCVA 
C.....CHECK TO SEE IF BULK MELT SOLIDIFICATION HAS LOCALLY OCCURRED AND,
C.....IF SO, INCORPORATE THE MATERIAL INTO THE BASEMAT
      CALL BULKSLD 
C.....IF THE SHELL HEATUP MODEL IS RUNNING, CHECK TO SEE IF MELT HAS 
C.....MADE CONTACT AND IF SO, SETUP AND CONTROL THIS CALCULATION.
      CALL SHELLCK
C.....CALL INCEPT & CHECK MELT-BASEMAT INTERFCIAL BOUNDARY CONDITIONS FOR
C.....INCEPTION OF CRUSTING AND/OR ABLATION AND SET APPRORIATE CONDITION. 
      CALL INCEPT
C.....CALL ENDBC TO CHECK IF CONDITIONS FOR CRUSTING AND/OR ABLATION CAN
C.....CAN BE SUSTAINED.  IF NOT, SET THE PROPER BOUNDARY CONDITION.
      CALL ENDBC
C.....CHECK IF ABLATION DEPTH OF BASEMAT CELLS IS LESS THAN THE MINIMUM
C.....HAS OCCURED AND IF SO REMHESH SO ABLATION INTO NEXT CELL CAN START.
      CALL REMESH(IFAILJ)
C.....IF BASEMAT EROSION HAS LOCALLY REDUCED THE NUMBER OF VERTICAL NODES  
C.....TO THREE, TERMINATE RUN INSTRUCTING USER TO INCREASE DEPTH.
      IF(IFAILJ.EQ.1) GO TO 1719
C.....CALL TRACKER TO SEE IF KT-TH CONSTITUENT IS EJECTED FROM RPV, IS 
C.....FORMING FROM CHEM REACTION, OR OTHER. OTHERWISE IT ISNT TRACKED.
      CALL TRACKER
C.....CALL CRUSTCK TO CHECK CRUST GROWTH LOGIC DEPENDING UPON
C.....USER MODEING ASSUMPTIONS. 
      CALL CRUSTCK
C.....BEFORE ENTERING ITERATION LOOP, CALCULATE MATERIAL PROPERITES OF
C.....STRUCTURE, MELT, AND DEBRIS ZONES (ASSUMED CONSTANT OVER TIMESTEP).
      CALL PROPEVL
C.....IF DETAILED WATER INVENTORY MODEL IS BEING USED, CALCULATE CURRENT
C.....DEPTHS, TEMPERATURES, AND VELOCITIES.
      CALL WATERCLC 
C....SAVE OLD DATA PRIOR TO INITIATION OF TIMESTEP.
      CALL SAVER
C.....CALL VELCALC AND SOLVE THE 1-D TRANSIENT MOMENTUM EQUATION FOR
C.....SPREADING VELOCITY USING AN APPROX. CONSERVATION OF MASS EQUATION.
      CALL VELCALC
C...................................................................... 
C.....THIS IS THE POINT OF THE OUTER LOOP FOR THE ITERATIVE SOLUTION OF 
C.....THE DETAILED COM AND COE EQUATIONS. 
      NITEN=0
 3928 CONTINUE
      NITEN=NITEN+1   
      IF(NITEN.GT.NENMAX) WRITE(2,*) 'WARNING: MELT COE CONVERGENCE FAIL
     1ED, T=',TIME
      IF(NITEN.GT.NENMAX) GO TO 3929      
C.....FIRST UPDATE MELT-TO-BASEMAT AND MELT/SOLDIFIED DEBRIS-TO- 
C.....ATMOSPHERE (WET OR DRY) HEAT TRANSFER COFFICIENTS.
      CALL HTCOEFC
C.....CALCULATE THE BASEMAT FORWARD ELIMINATION COEFFICIENTS BEFORE     
C.....SOLVING CONSERVATION OF MASS AND ENERGY IN THE MELT LAYER.
      CALL ELIMBM
C.....IF SHELL HEATUP CALC IS PERFORMED AND MELT HAS CONTACTED THE  
C.....SHELL, THEN CALCULATE THE SHELL FORWARD ELIMINATION COEFFICIENTS.
      CALL SHELL(IFAILJ)      
C.....IF MELT DEPTH ADJACENT TO SHELL EXCEEDS NODALIZED HEIGHT, TERMINATE
C.....RUN INSTRUCTING USER TO INCREASE NODALIZED SHELL HEIGHT.
      IF(IFAILJ.EQ.1) GO TO 1719
C...................................................................... 
C.....GIVEN THE NEW VELOCITIES AND CONCRETE FORWARD ELIMINATION COEFS.,
C.....SOLVE TDMA PROBLEMS FOR COM AND COE EQUATIONS. FIRST SOLVE FOR   
C.....HEIGHT INCREMENTS ASSUMING THAT THESE ARE INDEPENDENT OF CHANGES
C.....IN MELT ENTHALPY.  WITH THIS DATA, THE MELT ENTHALPY INCREMENTS 
C.....ARE CALCULATED.  THE HEIGHT INCREMENTS ARE THEN UPDATED GIVEN THE 
C.....CONVERGED ENTHALPY INCREMENTS.      
      NWRAP=0
 5020 CONTINUE
C.....CALCULATE HEIGHT INCREMENTS OR HEIGHTS DEPENDING UPON NWRAP..
      CALL HITEELM(NWRAP)
      IF(NWRAP.EQ.1) GO TO 5999 
C.....GIVEN THE VELOCITIES, HEIGHT & CONCRETE FORWARD ELIMINATION      
C.....COEFFICIENTS, SOLVE FOR THE BULK LIQUID ENTHALPY INCREMENTS.     
      CALL ENERELM
      NWRAP=1
      GO TO 5020      
 5999 CONTINUE
C.....GIVEN THE CURRENT BULK ENTHALPY INCREMENTS AND HEIGHTS, CONSTRUCT
C.....DEPENDENT VARIABLES AT THE END OF THE ITERATION.
      CALL UPDATE
C.....NOW CHECK SOLUTION FOR CONVERGENCE.
      NXSM=1
      DEMXI=ABS(DBLKEN(1))      
      DESUM=DEMXI     
      DO 6811 KIT=2,NUMNOD      
      IF(NACTIV(KIT).EQ.0) GO TO 6811     
      IF(NITEN.LE.5) GO TO 8332
      IF(HTOT(KIT).LT.HMINC) GO TO 6811
      GO TO 6811
 8332 CONTINUE
      NXSM=NXSM+1     
      DEBV=ABS(DBLKEN(KIT))     
      DESUM=DESUM+DEBV
      DEMXI=DMAX1(DEBV,DEMXI)   
 6811 CONTINUE
      DEAV=DESUM/FLOAT(NXSM)    
      IF(DEMXI.LE.DEMX.AND.DEAV.LE.DEAVMX) GO TO 3929
      GO TO 3928      
 3929 CONTINUE
C.....SOLUTION HAS CONVERGED; UPDATE ADDITIONAL DATA FOR I/O.
      CALL WRAPUP(IFINISH)
C.....WRITE OUT THE COMPUTED INFORMATION AT THE END-OF-TIMESTEP.
C.....FIRST SEE IF ITS TIME TO WRITE SPATIAL DISTRBUTION DATA. 
C.....OUT AT THIS POINT.
      IF(NTIMSPC.EQ.0) GO TO 8819 
      DO 8821 KPL=1,NTIMSPC
      FPLOT=(TIME-TIMSPC(KPL))/DTIME
      IF(FPLOT.LE.0.D0) GO TO 8821 
      IF(FPLOT.GT.1.D0) GO TO 8821
      CALL PLOTSPC(KPL)
      GO TO 8819
 8821 CONTINUE
 8819 CONTINUE 
C.....NOW SEE IF TEMPORAL DATA AT SELECTED NODES AND OTHER
C.....INFORMATION IS TO BE WRITTEN OUT AT THIS TIME.
      IF(NPLFREQ.EQ.0) GO TO 4477
      IF(NPLRND.LT.NPLFREQ) GO TO 4477
      IF(NPLTOT.GT.0) CALL PLOTTIM
      IF(NBPL.GT.0) CALL PLOTBM
      IF(NJET.GT.0) CALL PLOTJET
      IF(NWAT.EQ.2) CALL PLOTWAT
      WRITE(31,3111) TIME,XLEADE,ARSUM,TSHLMX
 3111 FORMAT(4(2X,E12.5))
 4477 CONTINUE
C.....NOW SEE IF ITS TIME TO WRITE OUT TEXT DATA TO THE ASCII 
C.....OUTPUT FILE.
      IF(NROUND.LT.NPFREQ) GO TO 4470     
      CALL PRINTS(NPRINT)     
 4470 CONTINUE
      GO TO 1700      
 1719 CONTINUE
C.....FINISH UP BY WRITING OUT DATA USEFUL FOR CORQUENCH INPUT.
      CALL CQSTART
      STOP  
      END