C...................................................................... 
C.....GIVEN THE TEMPERATURE OF WATER AND THE DRYWELL PRESSURE,
C.....SUBROUTINE TWENTH CALCULATES THE ENTHALPY AND THE DERIVATIVE
C.....OF THE TEMPERATURE WITH RESPECT TO ENTHALPY.  ENTHALPY CHANGE
C.....GOING FROM SATURATED LIQUID TO SATURATED VAPOR IS ASSUMED 
C.....TO BE 1 C.
C...................................................................... 
      SUBROUTINE TWENTH(E,T,P,DTDE)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      REAL(8) KL
      DATA TREF /273.15D0/
      CALL CONWAT(TSAT,KL,PL,CL,UL,HLV,EWL,EWV,CWV,SIGMA,P)
      IF(T.GE.TSAT) GO TO 10
      E=CL*(T-TREF)
      DTDE=1.0D0/CL
      GO TO 30
   10 CONTINUE
      IF(T.GT.TSAT+1.D0) GO TO 20
      E=EWL+HLV*(T-TSAT)
      DTDE=1.D0/HLV
      GO TO 30
   20 CONTINUE
      E=EWV+CWV*(T-(TSAT+1.D0))
      DTDE=1.D0/CWV
   30 CONTINUE
      RETURN
      END