C...................................................................... 
C.....GIVEN THE FLUID TEMPERATURE AND THE COLLAPSED DEPTHS OF THE
C.....FLUID CONSTITUENT MATERIALS, THIS ROUTINE CALCULATES THE
C.....VISCOSITIES, VISFLO AND VISFLM, OF THE LIQUID OXIDE AND 
C.....METAL PHASES AS WELL AS THE EFFECTIVE VISCOSITY, VISF, OF
C.....THE OXIDE-METAL MIXTURE.  
C...................................................................... 
      SUBROUTINE VISCF(T,HSEND,VISFLO,VISFLM,VISF,VISRE)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DIMENSION HMOL(28),HSEND(28)
      COMMON/PROPI/ NMATC,NMATFI,NMATFF,ICAOH2,ICACO3,IMCCO3,IFH2O,     
     1IVH2O,ICK2O,IVK2O,INA2O,ITIO2,ISIO2,ICAO,IMGO,IAL2O3,IFEO,IFE2O3, 
     2IFE3O4,IFE,ICR,INI,IZR,IU,IB4C,IB,ICR2O3,INIO,IUO2,IZRO2,IB2O3,   
     3NBCINT(999),NODES(999),NUMNOD,IMOX(28),IBAS,ILCS,ILL,NACTIV(999),     
     4NBFRZM,NBFRZO,NABLFM,NDRNFM,NTYPMT(999,999),NDOOR,NBMADJ,NUMSHV,   
     5NBSHL(999),NCRSTS(999),NUMSHH,NSKIPE,NACSH,NWAT,NPEND,NBCBOT,
     6NCRTOP,NBFZOE,NBFZME,NGEOM,NL(999,999),NFRSCT,NLOGSH,NADAB,NINVIS,
     7NSIMST,NSTEEL,NOVHT,NOVTK,NOVUM,NOVEM,NOVSIG,NPLLOC(999),NBPL,
     8IXP(999),IYP(999),NVTPE,NSOLTP,NSOLF,NINTF,IFLGA(999),ICTYPE,ICTC,
     9NPOURS,NSMP,NPED,NDOR,NSHL,NANULS,NSMPCV,NBOIL,NSWALL,NMVER,
     1NCRTEM,NTHINC,NVELP,NITMAX,NENMAX,NPRINT,NPFREQ,NTIMSPC,NPLFREQ,
     2NPLTOT,NJET,NJETP,NJETD,NJETND,NODCAP,NVELPW,NITMAXW,NENMXW,
     3IFLGJ(999),NBEDCQ,ISHELE
      COMMON/DATOVER/COVS,COVL,DHSOV,XMOLOV,ROVS,ROVL,TKOVS,TKOVL,VISOV,
     1EMOV,SIGOV
      COMMON/PRINTR/ QFEH2O,QCRH2O,QZRH2O,QFECO2,QCRCO2,QZRCO2,
     4XFH2OU,XFCAOH,XFMGCA,XFCACO,XZRMRE,XFEMRE,XCRMRE,XZRORE,XFEORE,   
     5XCRORE,XMH2O,XMCO2,XMCACO,XMMGCA,XMCAOH,TFWL,TFWS,TBWL,TBWS,      
     6TMCAL,TMCAS,TCAL,TCAS,TFOS,TFOL,TFMS,TFML,XVISC(28),SVISC(28),    
     7XMOL(28),FMMOL(28),ROM(28),ROMLIQ(28),AEQM(28,2),BEQM(28,2),
     8CEQM(28,2),ECL,ECS,ECAL,ECAS,EMCAL,EMCAS,EBWL,EBWS,EFWL,EFWS,    
     9STEF,GRAV,PI,TCS,TCL,CCL,CCS,RMASSL,WPCC,WPM,WPA,WPCS,ROC,RMASSS,   
     1ANGSHL,RSLAGL,RSLAGS,HNODT,VFAV,VGAV,QXAV,XWTSS(16),  
     2TSCS(2),TSCL(2),ESCS(2),ESCL(2),CCSS(2),CCSL(2),ROSTLS,ROSTLL,
     3XFRGAS,HMINC,TST(99),TSTOP(99),AINTP(99),BINTP(99),DRATIO(999),
     4XBCN(999),XDCN(999),XBLT(15),ADEC(99),BDEC(99),APOUR(16,99),
     5BPOUR(16,99),XWTC(14),BWIDTH,THCKCV,TMBOIL,TEBOIL,VFINT,ANGFAN,
     6ALPMAX,THSHL,XFCABL,XNDMIN,DVMX,DAVMX,DEAVMX,DEMX,TDC,QDCU,QDCUO2,
     7TSINJ,EINJ,DTINJ,TKINJ,ROEV,CPINJ,SURFT,VSINJ,EMINJ,TSINJO,EINJO,
     8DTINJO,TKINJO,ROEVO,CPINJO,SURFTO,VSINJO,EMINJO,XLEADE,ARSUM,
     9DBUBOX,UTRISE,TREMSH,DJET,DFALL,WEBER,FROUDE,XPSAITO,XPEPSTN,
     1FRAG,XMBEDT,XMBED(16),XLPENT,XLPENA,UJET,UFALL,HFALL,ERPV,
     2TJETT(99),DJETT(99),HWATP,XDOTJET,DVMXW,DAVMXW,DEMXW,DEAVMXW,
     3QJETW,XSTMJF,TINTSJF,ESAT,DRDOOR,DRANL,EI,QDCBUO2,QDCBU,
     4EBEDS,EBEDB
      COMMON/PRINTB/ELEVAT(999),ELOLD(999),XDIST(999,999),XBTW(999,999),
     1TEMP(999,999),ENTHP(999,999),EOLD(999,999),ENBLK(999),EBKOLD(999),
     2TBULK(999),HITE(16,999),HITOLD(16,999),HTOT(999),HTOLD(999),
     3HTCFT(999),HTCOEF(999),QFLUXT(999),QFLUXB(999),VEL(999),ELO(999),
     4VELOLD(999),SRSCOR(16),AREA(999),RAD(999),ARC(999),VOLCN(16),
     5VOID(999),VGJ(999),ZABLAT(999),ZABOLD(999),DCRUST(999),
     6DCROLD(999),DABCON(999),DABOLD(999),DFILMT(999),DFOLT(999),
     7SMFLX(4,999),XLSMF(4,999),TOTVOL,XFACMS(999),XMFLXA,XMCORT,
     8VCORT,TOTOX,TOTMET,QFLXT,QFLXB,TIME,DTIME,XMCOR(16),VCOR(16),
     9TCONI,RSAND,HDOWNC,TBOUND,EMISCN,PDRYWL,XDISTO(999),QOXT(999),
     1XLENSH,XBTWO(999),RCOMP,WDOOR,RSUMP,RSHELL,RPED,TPED,ELSMP,
     1TENDP(10,999),TFRZSH,TDEBRS,TKDEBR,PDEBR,CPDEBR,ENENDP(10,999),
     2ENOLDP(10,999),DXVERT,DXSNK,XDSTE(10,999),XBTE(10,999),HXLA(999),
     3HXLB(999),TSFEB(999),DCRS(999),DCRSLD(999),HCRS(16,999),
     4HCRSLD(16,999),THETE0(10,999),THETE1(10,999),QSHELL,QSHELE,TSHELI,
     5SIGOXE(999),FKOXE(999),RINJC,XLSEC,ANGSEC,ANINJC,XLCHAN,WCHNL,
     6TEFZX(999),TIMSPC(999),DXNODE(999),TNORM(999),FRCSOL(999),
     7ALPSPR(999),CRAMCON,HINTF,TSHLMX,XFRMX(999),XFROX(999),XFRTX(999),
     8XMLMX(999),XMLOX(999),XMLTX(999),XTOTX(999),TIMEO,TMAX,EDOWN(999),
     9HCP(999)
      DATA ZERO / 0.0 /
      DATA ONE / 1.0 /
      DATA R / 8.3143 /
      C2R3=2.0/3.0    
C.....CHECK IF VISCOSITY IS CALCULATED USING A USER-SPECIFIED VALUE; IF
C.....SO, CALL APPROPRIATE SUPPORT SUBROUTINE.
      IF(NOVUM.EQ.0) GO TO 7622
      CALL VISCS(T,HSEND,VISFLO,VISFLM,VISF,VISRE)
      GO TO 900
 7622 CONTINUE
C.....CALCULATE THE COLLAPSED MOLE FRACTIONS, HMOL, HERE.     
C.....CALCULATE THE OXIDE AND METAL LIQUID PHASE VISCOSITIES USING      
C.....THE DA ANDRADE FORMULA AT A MELTING TEMPERATURE CORRESPONDING     
C.....TO THE SOLIDUS TEMPERATURE.
      DNOM=ZERO
      DO 899 I=NMATFI,NMATFF    
      HMOL(I)=HSEND(I)*ROMLIQ(I)/FMMOL(I)
      DNOM=DNOM+HMOL(I)
  899 CONTINUE
      RDNOM=ZERO      
      IF (DNOM .NE. ZERO) RDNOM=ONE/DNOM  
      DO 999 I=NMATFI,NMATFF    
      HMOL(I)=HMOL(I)*RDNOM     
  999 CONTINUE
      ANUM=ZERO
      VNUM=ZERO
      DNOM=ZERO
      DO 399 I=NMATFI,NMATFF    
      IF (IMOX(I) .NE. 1) GO TO 399
      HMOLI=HMOL(I)   
      ANUM=ANUM+HMOLI*FMMOL(I)  
      VNUM=VNUM+HMOLI*FMMOL(I)/ROMLIQ(I)  
      DNOM=DNOM+HMOLI 
  399 CONTINUE
      IF(DNOM.LE.ZERO) GO TO 1810
      TEV=DMAX1(T,TFOS)
      RDNOM=ONE/DNOM  
      A=1000.0*ANUM*RDNOM
      V=1.0D+06*VNUM*RDNOM      
      VISFOS=6.12D-05*SQRT(TFOS*A)/V**C2R3
      Q=1.8033*TFOS**1.348      
      C=VISFOS/DEXP(Q/(R*TFOS))  
      VISFLO=C*DEXP(Q/(R*TEV))   
 1810 CONTINUE
      ANUM=ZERO
      VNUM=ZERO
      DNOM=ZERO
      DO 499 I=NMATFI,NMATFF    
      IF (IMOX(I) .NE. 0) GO TO 499
      HMOLI=HMOL(I)   
      ANUM=ANUM+HMOLI*FMMOL(I)  
      VNUM=VNUM+HMOLI*FMMOL(I)/ROMLIQ(I)  
      DNOM=DNOM+HMOLI 
  499 CONTINUE
      IF(DNOM.LE.ZERO) GO TO 1812
      TEV=DMAX1(T,TFMS)
      RDNOM=ONE/DNOM  
      A=1000.0*ANUM*RDNOM
      V=1.0D+06*VNUM*RDNOM      
      VISFMS=6.12D-05*SQRT(TFMS*A)/V**C2R3
      Q=1.8033*TFMS**1.348      
      C=VISFMS/DEXP(Q/(R*TFMS))  
      VISFLM=C*DEXP(Q/(R*TEV))   
 1812 CONTINUE
C.....CALCULATE THE OXIDE PHASE LIQUID VISCOSITY USING THE    
C.....METHODOLOGY OF CORCON MOD2 BASED UPON THE GEOLOGICAL    
C.....APPROACH OF SHAW.
      IF (HMOL(ISIO2) .LE. 0.01) GO TO 600
      SNUM=ZERO
      SDNOM=ZERO      
      SHMOL=ZERO      
      DO 599 I=NMATFI,NMATFF    
      IF (IMOX(I) .NE. 1) GO TO 599
      HMOLI=HMOL(I)   
      XVISCI=XVISC(I) 
      SNUM=SNUM+HMOLI*XVISCI*SVISC(I)     
      SDNOM=SDNOM+HMOLI*XVISCI  
      SHMOL=SHMOL+HMOLI
  599 CONTINUE
      TEV=DMAX1(T,TFOS)
      S=SNUM*HMOL(ISIO2)/(SDNOM*(SHMOL+HMOL(ISIO2)))
      VISFLG=DEXP(S*(1.0D+04/TEV-1.5)-6.4) 
      IF (VISFLO .LT. VISFLG) VISFLO=VISFLG
  600 CONTINUE
C.....CALCULATE THE EFFECTIVE VISCOSITY OF THE LIQUID OXIDE-METAL
C.....MIXTURE USING EITHER THE ISHII-ZUBER CORRELATION OR THE 
C.....RAMACCIOTTI CORRELATION.  HOWEVER, FIRST GET THE SOLID
C.....FRACTION OF THE MIXTURE.
      CALL SOLCALC(T,HSEND,VFM,VFO,VSOLM,VSOLO,VSOLT)
      VLIQT=ONE-VSOLT
      DENOM=ZERO
      IF(VLIQT.GT.ZERO) DENOM=ONE/VLIQT
      VISCC=DENOM*((ONE-VSOLM)*VFM*VISFLM+(ONE-VSOLO)*VFO*VISFLO)
      DENOM=ZERO
      IF(VSOLT.GT.ZERO) DENOM=ONE/VSOLT
      VISCD=DENOM*(VSOLM*VFM*VISFMS+VSOLO*VFO*VISFOS)
      IF(VSOLT.GT.ZERO) GO TO 1815
      VISF=VISCC      
      VISRE=VISF      
      GO TO 900
 1815 CONTINUE
C.....CALCULATE THE EFFECTIVE VISCOSITY OF THE LIQUID-SOLID   
C.....PARTICULATE MIXTURE USING THE EXPRESSION PROPOSED BY    
C.....ISHII AND ZUBER.
      VISNUM=VISCD    
      IF(VSOLT.LT.ONE.AND.VISCC.GT.ZERO) VISNUM=VISCC      
      IF(NVTPE.EQ.2) GO TO 88
      VFDMAX=ALPMAX      
      EXPFAC=(2.5*VFDMAX*(VISCD+0.4*VISCC))/(VISCD+VISCC)     
      VFPART=DMIN1(VSOLT/VFDMAX,ONE)
      VSDFAC=ONE/(ONE+1.D-07-VFPART)**EXPFAC
      GO TO 89
   88 CONTINUE
      ARG=2.5*CRAMCON*VSOLT
      VSDFAC=DEXP(ARG)
   89 CONTINUE
      VISF=VSDFAC*VISNUM
      VISRE=VISF      
  900 CONTINUE
      RETURN
      END