C...................................................................... 
C.....SUBROUTINE TEN EVALUATES THE MELT SURFACE TENSION GIVEN THE
C.....COLLAPSED MELT HEIGHT VECTOR, H.    
C...................................................................... 
      SUBROUTINE TEN(TPASS,H,SIG)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON/PROPI/ NMATC,NMATFI,NMATFF,ICAOH2,ICACO3,IMCCO3,IFH2O,     
     1IVH2O,ICK2O,IVK2O,INA2O,ITIO2,ISIO2,ICAO,IMGO,IAL2O3,IFEO,IFE2O3, 
     2IFE3O4,IFE,ICR,INI,IZR,IU,IB4C,IB,ICR2O3,INIO,IUO2,IZRO2,IB2O3,   
     3NBCINT(999),NODES(999),NUMNOD,IMOX(28),IBAS,ILCS,ILL,NACTIV(999),     
     4NBFRZM,NBFRZO,NABLFM,NDRNFM,NTYPMT(999,999),NDOOR,NBMADJ,NUMSHV,   
     5NBSHL(999),NCRSTS(999),NUMSHH,NSKIPE,NACSH,NWAT,NPEND,NBCBOT,
     6NCRTOP,NBFZOE,NBFZME,NGEOM,NL(999,999),NFRSCT,NLOGSH,NADAB,NINVIS,
     7NSIMST,NSTEEL,NOVHT,NOVTK,NOVUM,NOVEM,NOVSIG,NPLLOC(999),NBPL,
     8IXP(999),IYP(999),NVTPE,NSOLTP,NSOLF,NINTF,IFLGA(999),ICTYPE,ICTC,
     9NPOURS,NSMP,NPED,NDOR,NSHL,NANULS,NSMPCV,NBOIL,NSWALL,NMVER,
     1NCRTEM,NTHINC,NVELP,NITMAX,NENMAX,NPRINT,NPFREQ,NTIMSPC,NPLFREQ,
     2NPLTOT,NJET,NJETP,NJETD,NJETND,NODCAP,NVELPW,NITMAXW,NENMXW,
     3IFLGJ(999),NBEDCQ,ISHELE
      COMMON/DATOVER/COVS,COVL,DHSOV,XMOLOV,ROVS,ROVL,TKOVS,TKOVL,VISOV,
     1EMOV,SIGOV
      DIMENSION H(28) 
      DATA SIGM/1.73D0/
      DATA SIGO/0.52D0/
      DATA ONE/1.D0/  
      DATA ZERO/0.D0/ 
C.....CHECK IF INPUT DATA IS BEING USED TO OVERWRITE THE SURFACE 
C.....TENSION DATA AND IF SO, SET ACCORDINGLY.
      IF(NOVSIG.EQ.0) GO TO 887
      SIG=SIGOV
      GO TO 4788 
C.....GENERAL CASE DONE HERE.
  887 CONTINUE
      HT=ZERO
      HTM=ZERO
      HTO=ZERO
      DO 399 I=NMATFI,NMATFF    
      HMOLI=H(I)      
      HT=HT+HMOLI     
      IF(IMOX(I).NE.1) GO TO 299
      HTO=HTO+HMOLI   
      GO TO 399
  299 CONTINUE
      HTM=HTM+HMOLI   
  399 CONTINUE
      DENOM=0.D0      
      IF(HT.GT.0.D0) DENOM=ONE/HT
      VFLM=HTM*DENOM  
      VFLO=HTO*DENOM  
      SIG=VFLM*SIGM+VFLO*SIGO   
      SIG=DMAX1(SIGO,SIG)
      SIG=DMIN1(SIGM,SIG)
 4788 CONTINUE
      RETURN
      END