C...................................................................... 
C.....BEFORE ENTERING ITERATION LOOP, CALCULATE MATERIAL PROPERITES OF
C.....VARIOUS STRUCTURE, MELT, AND DEBRIS ZONES; THESE ARE ASSUMED
C.....CONSTANT OVER THE TIMESTEP.
C...................................................................... 
      SUBROUTINE PROPEVL
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      REAL(8) KL
      DIMENSION HSEND(28)
      COMMON/CATCHR/A(999),B(999),C(999),D(999),P(999),Q(999),
     1RECON(999),DELVEL(999),DSRDT(999),DELHTS(999),EMAX(999,999),
     2DBLKEN(999),DELHIT(16,999),SOURCE(16,999),SRCTOT(999),
     3HCROLD(16,999),DCDOT(999),HCRUST(16,999),DFILM(16,999),
     4DFMOLD(16,999),DENOLD(999),SIGOX(999),SIGCON(999),BET(999),
     5TFZX(999),TFZC(999),TKX(999),TKM(999),THETO(999,999),
     6THET1(999,999),OMEG0(4,999),OMEG1(4,999),TAO0(999),TAO1(999),
     7SIG0(999),SIG1(999),TARGB(999),DADOT(999),DADOTG(999),
     8XLOLD(4,999),VISREX(999),TATMS(999),HTMP(999),DHTMP(999),
     9HTMOLD(999)
      COMMON/CATCHI/NUMS(4,999),NUMOLD(4,999),NTRACK(16),NSUMP(999),
     1NPASSG(999),NCRSTM(999),NCRRT(999),NPASS(999),NBURN,NBURNO     
      COMMON/PRINTB/ELEVAT(999),ELOLD(999),XDIST(999,999),XBTW(999,999),
     1TEMP(999,999),ENTHP(999,999),EOLD(999,999),ENBLK(999),EBKOLD(999),
     2TBULK(999),HITE(16,999),HITOLD(16,999),HTOT(999),HTOLD(999),
     3HTCFT(999),HTCOEF(999),QFLUXT(999),QFLUXB(999),VEL(999),ELO(999),
     4VELOLD(999),SRSCOR(16),AREA(999),RAD(999),ARC(999),VOLCN(16),
     5VOID(999),VGJ(999),ZABLAT(999),ZABOLD(999),DCRUST(999),
     6DCROLD(999),DABCON(999),DABOLD(999),DFILMT(999),DFOLT(999),
     7SMFLX(4,999),XLSMF(4,999),TOTVOL,XFACMS(999),XMFLXA,XMCORT,
     8VCORT,TOTOX,TOTMET,QFLXT,QFLXB,TIME,DTIME,XMCOR(16),VCOR(16),
     9TCONI,RSAND,HDOWNC,TBOUND,EMISCN,PDRYWL,XDISTO(999),QOXT(999),
     1XLENSH,XBTWO(999),RCOMP,WDOOR,RSUMP,RSHELL,RPED,TPED,ELSMP,
     1TENDP(10,999),TFRZSH,TDEBRS,TKDEBR,PDEBR,CPDEBR,ENENDP(10,999),
     2ENOLDP(10,999),DXVERT,DXSNK,XDSTE(10,999),XBTE(10,999),HXLA(999),
     3HXLB(999),TSFEB(999),DCRS(999),DCRSLD(999),HCRS(16,999),
     4HCRSLD(16,999),THETE0(10,999),THETE1(10,999),QSHELL,QSHELE,TSHELI,
     5SIGOXE(999),FKOXE(999),RINJC,XLSEC,ANGSEC,ANINJC,XLCHAN,WCHNL,
     6TEFZX(999),TIMSPC(999),DXNODE(999),TNORM(999),FRCSOL(999),
     7ALPSPR(999),CRAMCON,HINTF,TSHLMX,XFRMX(999),XFROX(999),XFRTX(999),
     8XMLMX(999),XMLOX(999),XMLTX(999),XTOTX(999),TIMEO,TMAX,EDOWN(999),
     9HCP(999)
      COMMON/HCONS/HMETAL(999),HOXIDE(999)  
      COMMON/PROPI/ NMATC,NMATFI,NMATFF,ICAOH2,ICACO3,IMCCO3,IFH2O,     
     1IVH2O,ICK2O,IVK2O,INA2O,ITIO2,ISIO2,ICAO,IMGO,IAL2O3,IFEO,IFE2O3, 
     2IFE3O4,IFE,ICR,INI,IZR,IU,IB4C,IB,ICR2O3,INIO,IUO2,IZRO2,IB2O3,   
     3NBCINT(999),NODES(999),NUMNOD,IMOX(28),IBAS,ILCS,ILL,NACTIV(999),     
     4NBFRZM,NBFRZO,NABLFM,NDRNFM,NTYPMT(999,999),NDOOR,NBMADJ,NUMSHV,   
     5NBSHL(999),NCRSTS(999),NUMSHH,NSKIPE,NACSH,NWAT,NPEND,NBCBOT,
     6NCRTOP,NBFZOE,NBFZME,NGEOM,NL(999,999),NFRSCT,NLOGSH,NADAB,NINVIS,
     7NSIMST,NSTEEL,NOVHT,NOVTK,NOVUM,NOVEM,NOVSIG,NPLLOC(999),NBPL,
     8IXP(999),IYP(999),NVTPE,NSOLTP,NSOLF,NINTF,IFLGA(999),ICTYPE,ICTC,
     9NPOURS,NSMP,NPED,NDOR,NSHL,NANULS,NSMPCV,NBOIL,NSWALL,NMVER,
     1NCRTEM,NTHINC,NVELP,NITMAX,NENMAX,NPRINT,NPFREQ,NTIMSPC,NPLFREQ,
     2NPLTOT,NJET,NJETP,NJETD,NJETND,NODCAP,NVELPW,NITMAXW,NENMXW,
     3IFLGJ(999),NBEDCQ,ISHELE
      COMMON/PRINTR/ QFEH2O,QCRH2O,QZRH2O,QFECO2,QCRCO2,QZRCO2,
     4XFH2OU,XFCAOH,XFMGCA,XFCACO,XZRMRE,XFEMRE,XCRMRE,XZRORE,XFEORE,   
     5XCRORE,XMH2O,XMCO2,XMCACO,XMMGCA,XMCAOH,TFWL,TFWS,TBWL,TBWS,      
     6TMCAL,TMCAS,TCAL,TCAS,TFOS,TFOL,TFMS,TFML,XVISC(28),SVISC(28),    
     7XMOL(28),FMMOL(28),ROM(28),ROMLIQ(28),AEQM(28,2),BEQM(28,2),
     8CEQM(28,2),ECL,ECS,ECAL,ECAS,EMCAL,EMCAS,EBWL,EBWS,EFWL,EFWS,    
     9STEF,GRAV,PI,TCS,TCL,CCL,CCS,RMASSL,WPCC,WPM,WPA,WPCS,ROC,RMASSS,   
     1ANGSHL,RSLAGL,RSLAGS,HNODT,VFAV,VGAV,QXAV,XWTSS(16),  
     2TSCS(2),TSCL(2),ESCS(2),ESCL(2),CCSS(2),CCSL(2),ROSTLS,ROSTLL,
     3XFRGAS,HMINC,TST(99),TSTOP(99),AINTP(99),BINTP(99),DRATIO(999),
     4XBCN(999),XDCN(999),XBLT(15),ADEC(99),BDEC(99),APOUR(16,99),
     5BPOUR(16,99),XWTC(14),BWIDTH,THCKCV,TMBOIL,TEBOIL,VFINT,ANGFAN,
     6ALPMAX,THSHL,XFCABL,XNDMIN,DVMX,DAVMX,DEAVMX,DEMX,TDC,QDCU,QDCUO2,
     7TSINJ,EINJ,DTINJ,TKINJ,ROEV,CPINJ,SURFT,VSINJ,EMINJ,TSINJO,EINJO,
     8DTINJO,TKINJO,ROEVO,CPINJO,SURFTO,VSINJO,EMINJO,XLEADE,ARSUM,
     9DBUBOX,UTRISE,TREMSH,DJET,DFALL,WEBER,FROUDE,XPSAITO,XPEPSTN,
     1FRAG,XMBEDT,XMBED(16),XLPENT,XLPENA,UJET,UFALL,HFALL,ERPV,
     2TJETT(99),DJETT(99),HWATP,XDOTJET,DVMXW,DAVMXW,DEMXW,DEAVMXW,
     3QJETW,XSTMJF,TINTSJF,ESAT,DRDOOR,DRANL,EI,QDCBUO2,QDCBU,
     4EBEDS,EBEDB
      COMMON /WATVARS/FCRUST(999),VLW(999),VLWOLD(999),DWAT(999),
     1DWATOLD(999),EWAT(999),EWATOLD(999),TWAT(999),CORDDC(999),
     2DSRDC(999),DHDC(999),TSRDC,TINTDC,HWATB(999),TSURFW(999),XMS(999),
     3XMST,XINTS,ESRDTW(999),TSRDTW(999),DSRDTW(999),TSRDW,TINTDW,
     4TWATI,ELDCO(999),ELDCX(999,99),CRDCX(999,99),TIMINJ(999,99),
     5XDTINJ(999,99),TDTINJ(999,99),ELWATI,XMWAT,XMWATO,XBALW,
     6HDRY(999),EINTW,XMCT(199),XMCDT(16,999),TMPCDT(999),CMPCDT(999),
     7FDC(999),FCOV(999),FBED(999),FHEAT(999),XFACJ(999),
     8XMBEDJ(16,999),XMBEDJT(999),PBED,QBED(999),QWATER(999),
     9QSURFACE(999),QWATERT(999),HBED(999),POROSBED,XMCRDT(16,999),
     1XMCRT(999),XMBDINT(999),XMT(999)
      COMMON/BLKHT/TKMLT,PM,CM,UM,EMISM,SIGMAM,TKNC,PNC,CNC,UNC    
      COMMON/BASPR/ HBMT(999,999,16),HBMOLD(999,999,16) 
      COMMON/DEFUNC/CPLIQP,CPSOLP,EFOSP,EFOLP,EFMSP,EFMLP     
      COMMON/PROPB/CPBM(999),FKB(999,999),DENB(999,999),DTDEB(999,999),
     1EMIBM(999),DENCRS(999),ENCRS(999),FKRF(999),DENRF(999),CPRF(999) 
      COMMON/PROPM/DTDEM(999),CPMLT(999),FKMLT(999),DENMLT(999),
     1SIGMLT(999),UMMLT(999),EMIMLT(999)      
C.....CALCULATE WATER SATURATION TEMPERATURE IF NEEDED.
      IF(NWAT.GT.0) CALL CONWAT(TSAT,KL,PL,CL,UL,HLV,EWL,EWV,CWV,SIGMA,
     1PDRYWL)
C.....FIRST GET PARTICLE BED PROPERTIES WHICH AT THIS POINT ARE ONLY
C.....THE SPECIFIC ENTHALPIES AT SATURATION TEMPERATURE IF WATER IS
C.....PRESENT OR AT ABOVE STRUCTURE TEMPERATURE IF WATER IS ABSENT.
      EBEDS=0.D0
      EBEDB=0.D0
      IF(XMBEDT.LE.0.D0) GO TO 4539
      HSUM=0.E0
      DO 4538 KTP=1,15
      CALL INDEX(KTP,KJ)
      HSEND(KJ)=XMBED(KTP)/ROM(KJ)
      HSUM=HSUM+HSEND(KJ)
 4538 CONTINUE
      HSEND(10)=(WPCS*XMBED(16))/ROM(ISIO2)   
      HSEND(11)=(WPCC*XMBED(16))/ROM(ICAO)    
      HSEND(12)=(WPM*XMBED(16))/ROM(IMGO)     
      HSEND(13)=(WPA*XMBED(16))/ROM(IAL2O3)   
      HSUM=HSUM+HSEND(10)+HSEND(11)+HSEND(12)+HSEND(13)
      CALL ETF(EBEDB,HSEND,TBOUND,DPASS)    
      IF(NWAT.EQ.0) GO TO 4539
      CALL ETF(EBEDS,HSEND,TSAT,DPASS)    
 4539 CONTINUE
      DO 3735 J=1,NUMNOD
      IF(NACTIV(J).EQ.0) GO TO 3735
C.....NOW CALCULATE MELT PROPERTIES AT ACTIVE NODES.    
      ALPSPR(J)=1.D0
      IF(HTOT(J).LE.0.D0) GO TO 1516      
      CALL MASFRA(HITE,ROMLIQ,J,RSLAGL,ROC,DENMLT(J),0)
      CALL ASINEA(HITE,J,HSEND,ROMLIQ,WPCC,WPM,WPA,WPCS,ROC,RSLAGL,0)   
      CALL TEF(ENBLK(J),HSEND,TPASS,DTDE) 
      DTDEM(J)=DTDE   
      CPMLT(J)=CPLIQP 
      CALL CONDF(TBULK(J),HSEND,FKO,FKM,FKMLT(J))   
      CALL TEN(TBULK(J),HSEND,SIGMLT(J))  
      CALL VISCF(TBULK(J),HSEND,VISFLO,VISFLM,UMMLT(J),VISREX(J))
      CALL EMISF(TBULK(J),HSEND,EMIMLT(J))
      CALL SOLCALC(TBULK(J),HSEND,VFM,VFO,VSOLM,VSOLO,ALPSPR(J))
      TDOWN=TBOUND    
      IF(NWAT.EQ.0) GO TO 2232
      IF(DWAT(J).LE.0.D0) GO TO 2232
      TDOWN=TSAT+1.D0  
 2232 CONTINUE
      CALL ETF(EDOWN(J),HSEND,TDOWN,DTDE)    
 1516 CONTINUE
C.....IF CRUST GROWTH IS SPECIFIED, CALCULATE CRUST PROPERTIES.
      IF(NBCINT(J).EQ.1.OR.NBCINT(J).EQ.4.OR.NBCINT(J).EQ.5) GO TO 931  
      TFZX(J)=TFOS    
      IF(NCRSTM(J).EQ.2) TFZX(J)=TFMS    
      IF(NBCINT(J).EQ.3.OR.NBCINT(J).EQ.7.OR.NBCINT(J).EQ.9) GO TO 931  
      CALL ASINEA(HCRUST,J,HSEND,ROM,WPCC,WPM,WPA,WPCS,ROC,RSLAGS,NCRSTM
     1(J))  
      CALL TEF(ENBLK(J),HSEND,TPASS,DTDE) 
      IF(NCRSTM(J).EQ.2) GO TO 58
      HFREEZ=EFOLP-EFOSP
      ENCRS(J)=EFOSP  
      GO TO 59
   58 CONTINUE
      HFREEZ=EFMLP-EFMSP
      ENCRS(J)=EFMSP  
   59 CONTINUE
      CALL CONDF(TFZX(J),HSEND,FKO,FKM,TKX(J))      
      CALL MASFRA(HCRUST,ROM,J,RSLAGS,ROC,DENCR,NCRSTM(J))    
      DENCRS(J)=DENCR 
      SIGOX(J)=(DENCR*HFREEZ)/(2.D0*DTIME)
  931 CONTINUE
C.....CALCULATE ABLATING SUBSTRATE PROPERTIES IF ABLATION IS OCCURING.  
      IF(NBCINT(J).GT.3) GO TO 935
      NDRIVE=1
      IF(NTYPMT(1,J).GT.3) GO TO 2719     
      CPBM(J)=CCSS(NL(1,J))     
      CALL EMISC(TEMP(1,J),NTYPMT(1,J),EMIBM(J),NL(1,J))      
      GO TO 936
 2719 CONTINUE
      CALL ASINED(1,J,HSEND,ROM,WPCC,WPM,WPA,WPCS,ROC,RSLAGS,0)
      CALL TEF(ENTHP(1,J),HSEND,TPASS,DTDE)
      CPBM(J)=CPSOLP  
      CALL EMISF(TEMP(1,J),HSEND,EMIBM(J))
      GO TO 936
  935 CONTINUE
      NDRIVE=3
      ZCOMP=XDISTO(J)-ZABLAT(J) 
      IP=2  
      IF(ZCOMP.LT.XBTWO(J)) IP=1
      IF(NTYPMT(IP,J).GT.3) GO TO 937     
      TFZC(J)=TSCS(NL(IP,J))    
      TLIQP=TSCL(NL(IP,J))      
      HABL=ESCL(NL(IP,J))-ESCS(NL(IP,J))  
      DTDEB(IP,J)=1./CCSS(NL(IP,J))
      DENB(IP,J)=ROC  
      IF(NL(IP,J).EQ.2) DENB(IP,J)=ROSTLS
      DRATIO(J)=RMASSS/RSLAGL   
      IF(NL(IP,J).EQ.2) DRATIO(J)=ROSTLS/ROSTLL    
      CALL CONDC(TEMP(IP,J),NTYPMT(IP,J),FKB(IP,J),NL(IP,J))  
      CALL CONDC(TLIQP,NTYPMT(IP,J),FKRF(J),NL(IP,J))
      CPBM(J)=CCSS(NL(IP,J))    
      CPRF(J)=CCSL(NL(IP,J))    
      DENRF(J)=RSLAGL*ROC
      IF(NL(IP,J).EQ.2) DENRF(J)=ROSTLL  
      CALL EMISC(TFZC(J),NTYPMT(IP,J),EMIBM(J),NL(IP,J))      
      GO TO 938
  937 CONTINUE
      CALL ASINED(IP,J,HSEND,ROM,WPCC,WPM,WPA,WPCS,ROC,RSLAGS,0)
      CALL TEF(ENTHP(IP,J),HSEND,TPASS,DTDE)
      IF(NTYPMT(IP,J).EQ.5) GO TO 939     
      TFZC(J)=TFMS    
      TLIQP=TFML      
      HABL=EFMLP-EFMSP
      GO TO 940
  939 CONTINUE
      TFZC(J)=TFOS    
      TLIQP=TFOL      
      HABL=EFOLP-EFOSP
  940 CONTINUE
      DTDEB(IP,J)=DTDE
      CPBM(J)=CPSOLP  
      CPRF(J)=CPLIQP  
      CALL MASFRD(ROMLIQ,IP,J,RSLAGL,ROC,DENRF(J))  
      CALL MASFRD(ROM,IP,J,RSLAGS,ROC,DENB(IP,J))   
      DRATIO(J)=DENB(IP,J)/DENRF(J)
      CALL CONDF(TFZC(J),HSEND,FKO,FKM,FKB(IP,J))   
      CALL CONDF(TLIQP,HSEND,FKO,FKM,FKRF(J))
      CALL EMISF(TFZC(J),HSEND,EMIBM(J))  
  938 CONTINUE
      IF(IP.EQ.1) GO TO 942     
      FKB(IP-1,J)=FKB(IP,J)     
      DENB(IP-1,J)=DENB(IP,J)   
      DTDEB(IP-1,J)=DTDEB(IP,J) 
      BET(J)=FKB(IP,J)
      GO TO 943
  942 CONTINUE
      ZLINT=XBTWO(J)-ZCOMP      
      ZRINT=XDISTO(J)-XBTWO(J)  
      IP1=IP+1
      IF(NTYPMT(IP1,J).GT.3) GO TO 944    
      CALL CONDC(TEMP(IP1,J),NTYPMT(IP1,J),FKB(IP1,J),NL(IP1,J))
      CALL TEC(ENTHP(IP1,J),EMAX(IP1,J),TPASS,DTDE,RMASS,YCACO3,YMCCO3,Y
     1CAOH2,YFH2O,NL(IP1,J))    
      DTDEB(IP1,J)=DTDE
      DENB(IP1,J)=ROC 
      IF(NL(IP1,J).EQ.2) DENB(IP1,J)=ROSTLS
      GO TO 945
  944 CONTINUE
      CALL ASINED(IP1,J,HSEND,ROMLIQ,WPCC,WPM,WPA,WPCS,ROC,RSLAGS,0)    
      CALL ETF(EPS,HSEND,TEMP(IP1,J),DTDEB(IP1,J))  
      CALL CONDF(TEMP(IP1,J),HSEND,FKO,FKM,FKB(IP1,J))
      CALL MASFRD(ROM,IP1,J,RSLAGS,ROC,DENB(IP1,J)) 
  945 CONTINUE
      BET(J)=(ZABLAT(J)*FKB(IP,J)*FKB(IP1,J))/(FKB(IP,J)*ZRINT+FKB(IP1,J
     1)*ZLINT)
  943 CONTINUE
      HEVAL=HABL      
      IF(NTYPMT(IP,J).GT.3) GO TO 5121    
      IF(NL(IP,J).EQ.2) GO TO 5121
      IF(DADOTG(J).GE.0.D0) GO TO 5121    
      C1=ESCL(NL(IP,J))
      C2=BET(J)*(TFZC(J)-TEMP(2,J))
      C3=DENB(IP,J)*ZABLAT(J)*ABS(DADOTG(J))
      HEVAL=C1-C2/C3  
      HEVAL=DMAX1(HEVAL,HABL)   
      HEVAL=DMIN1(ESCL(NL(IP,J)),HEVAL)   
 5121 CONTINUE
      SIGCON(J)=(DENB(IP,J)*HEVAL)/(2.D0*DTIME)     
C.....CALCULATE MOLTEN FILM PROPERTIES IF FILM EXISTS.
      IF(NBCINT(J).EQ.5.OR.NBCINT(J).EQ.8.OR.NBCINT(J).EQ.9) GO TO 946  
      GO TO 936
  946 CONTINUE
      CALL ASINEA(DFILM,J,HSEND,ROMLIQ,WPCC,WPM,WPA,WPCS,ROC,RSLAGL,0)  
      CALL CONDF(TFZC(J),HSEND,FKO,FKM,TKM(J))      
  936 CONTINUE
      DO 3719 KV=NDRIVE,NODES(J)
      IF(NTYPMT(KV,J).GT.3) GO TO 950     
      CALL CONDC(TEMP(KV,J),NTYPMT(KV,J),FKB(KV,J),NL(KV,J))  
      IF(NL(KV,J).EQ.2) GO TO 949
      DENB(KV,J)=ROC  
      GO TO 3719      
  949 CONTINUE
      DENB(KV,J)=ROSTLS
      GO TO 3719      
  950 CONTINUE
      CALL ASINED(KV,J,HSEND,ROM,WPCC,WPM,WPA,WPCS,ROC,RSLAGS,0)
      CALL CONDF(TEMP(KV,J),HSEND,FKO,FKM,FKB(KV,J))
      CALL MASFRD(ROM,KV,J,RSLAGS,ROC,DENB(KV,J))   
 3719 CONTINUE
 3735 CONTINUE
C.....IF MELT HAS CONTACTED THE SHELL AND THE SHELL HEATUP CALCULATION  
C.....IS BEING PERFORMED, CALCULATE LOCAL SHELL CRUST PROPERTIES.
      IF(NSKIPE.EQ.0) GO TO 6211
      IF(ISHELE.EQ.1) GO TO 6211
      IF(NACSH.EQ.0) GO TO 6211 
      DO 6212 KV=2,NUMSHV
      IF(NBSHL(KV).EQ.1) GO TO 6212
      CALL ASINEA(HCRS,KV,HSEND,ROM,WPCC,WPM,WPA,WPCS,ROC,RSLAGL,NCRSTS(
     1KV))  
      CALL TEF(ENBLK(NBMADJ),HSEND,TPASS,DTDE)      
      IF(NCRSTS(KV).EQ.2) GO TO 6213     
      TEFZX(KV)=TFOS  
      IF(NCRTEM.EQ.1) TEFZX(KV)=TREMSH    
      TEFZX(KV)=DMAX1(TFOS,TREMSH)
      HOX=EFOLP-EFOSP 
      GO TO 6214      
 6213 CONTINUE
      TEFZX(KV)=TFMS  
      IF(NCRTEM.EQ.1) TEFZX(KV)=TREMSH    
      TEFZX(KV)=DMAX1(TFMS,TREMSH)
      HOX=EFMLP-EFMSP 
 6214 CONTINUE
      CALL MASFRA(HCRS,ROM,KV,RSLAGL,ROC,DENCA,NCRSTS(KV))    
      SIGOXE(KV)=(DENCA*HOX)/(2.D0*DTIME) 
      CALL CONDF(TEFZX(KV),HSEND,FKO,FKM,FKOXE(KV)) 
 6212 CONTINUE
 6211 CONTINUE
      RETURN
      END