C...................................................................... 
C.....SUBROUTINE DENSS  DETERMINES THE DENSITY AS A FUNCTION OF
C.....TEMPERATURE FOR CARBON STEEL.
C...................................................................... 
      SUBROUTINE DENSS(T,P)     
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON/PROPI/ NMATC,NMATFI,NMATFF,ICAOH2,ICACO3,IMCCO3,IFH2O,     
     1IVH2O,ICK2O,IVK2O,INA2O,ITIO2,ISIO2,ICAO,IMGO,IAL2O3,IFEO,IFE2O3, 
     2IFE3O4,IFE,ICR,INI,IZR,IU,IB4C,IB,ICR2O3,INIO,IUO2,IZRO2,IB2O3,   
     3NBCINT(999),NODES(999),NUMNOD,IMOX(28),IBAS,ILCS,ILL,NACTIV(999),     
     4NBFRZM,NBFRZO,NABLFM,NDRNFM,NTYPMT(999,999),NDOOR,NBMADJ,NUMSHV,   
     5NBSHL(999),NCRSTS(999),NUMSHH,NSKIPE,NACSH,NWAT,NPEND,NBCBOT,
     6NCRTOP,NBFZOE,NBFZME,NGEOM,NL(999,999),NFRSCT,NLOGSH,NADAB,NINVIS,
     7NSIMST,NSTEEL,NOVHT,NOVTK,NOVUM,NOVEM,NOVSIG,NPLLOC(999),NBPL,
     8IXP(999),IYP(999),NVTPE,NSOLTP,NSOLF,NINTF,IFLGA(999),ICTYPE,ICTC,
     9NPOURS,NSMP,NPED,NDOR,NSHL,NANULS,NSMPCV,NBOIL,NSWALL,NMVER,
     1NCRTEM,NTHINC,NVELP,NITMAX,NENMAX,NPRINT,NPFREQ,NTIMSPC,NPLFREQ,
     2NPLTOT,NJET,NJETP,NJETD,NJETND,NODCAP,NVELPW,NITMAXW,NENMXW,
     3IFLGJ(999),NBEDCQ,ISHELE
      COMMON/DATSIMS/TSIS,TSIL,CSIS,CSIL,DHSIL,RSIS,RSIL,TKSIS,TKSIL,
     1ESIL,XCSI(16)
      IF(NSIMST.EQ.0) GO TO 33
      P=RSIS
      IF(T.GT.TSIS) P=RSIL
      GO TO 200
   33 CONTINUE 
      IF(T.LT.1811.D0) GO TO 10 
      P=7010.D0-8.3419D-1*(T-1811.D0)     
      GO TO 200
   10 CONTINUE
      IF(T.LE.1185.D0) GO TO 20 
      FL=-1.7680D0+2.33D-3*T   
      GO TO 50
   20 CONTINUE
      DT=T-300.D0     
      DT2=DT*DT
      DT3=DT*DT2      
      FL=9.D-3+1.21D-3*DT+6.504D-7*DT2-3.14D-10*DT3 
   50 CONTINUE
      DENOM=1.D0+1.D-2*FL
      P=7867.D0/(DENOM*DENOM*DENOM)
  200 CONTINUE
      RETURN
      END