C...................................................................... 
C.....SUBROUTINE SHELLM EVALUATES THE SHELL-TO-MELT HEAT TRANSFER
C.....COEFFICIENT USING THE MAXIMUM EXPRESSION BETWEEN A JET  
C.....IMPINGEMENT CORRELATION AND THEOFANAOUS'S INCLINED PLATE
C.....BUBBLING HEAT TRANSFER COEFFICIENT. 
C...................................................................... 
      SUBROUTINE SHELLM(TB,VG,V,VOID,CM,PM,TKM,UM,HEIGHT,HSHELL,XLENSH) 
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON/PROPI/ NMATC,NMATFI,NMATFF,ICAOH2,ICACO3,IMCCO3,IFH2O,     
     1IVH2O,ICK2O,IVK2O,INA2O,ITIO2,ISIO2,ICAO,IMGO,IAL2O3,IFEO,IFE2O3, 
     2IFE3O4,IFE,ICR,INI,IZR,IU,IB4C,IB,ICR2O3,INIO,IUO2,IZRO2,IB2O3,   
     3NBCINT(999),NODES(999),NUMNOD,IMOX(28),IBAS,ILCS,ILL,NACTIV(999),     
     4NBFRZM,NBFRZO,NABLFM,NDRNFM,NTYPMT(999,999),NDOOR,NBMADJ,NUMSHV,   
     5NBSHL(999),NCRSTS(999),NUMSHH,NSKIPE,NACSH,NWAT,NPEND,NBCBOT,
     6NCRTOP,NBFZOE,NBFZME,NGEOM,NL(999,999),NFRSCT,NLOGSH,NADAB,NINVIS,
     7NSIMST,NSTEEL,NOVHT,NOVTK,NOVUM,NOVEM,NOVSIG,NPLLOC(999),NBPL,
     8IXP(999),IYP(999),NVTPE,NSOLTP,NSOLF,NINTF,IFLGA(999),ICTYPE,ICTC,
     9NPOURS,NSMP,NPED,NDOR,NSHL,NANULS,NSMPCV,NBOIL,NSWALL,NMVER,
     1NCRTEM,NTHINC,NVELP,NITMAX,NENMAX,NPRINT,NPFREQ,NTIMSPC,NPLFREQ,
     2NPLTOT,NJET,NJETP,NJETD,NJETND,NODCAP,NVELPW,NITMAXW,NENMXW,
     3IFLGJ(999),NBEDCQ,ISHELE
      COMMON/PRINTR/ QFEH2O,QCRH2O,QZRH2O,QFECO2,QCRCO2,QZRCO2,
     4XFH2OU,XFCAOH,XFMGCA,XFCACO,XZRMRE,XFEMRE,XCRMRE,XZRORE,XFEORE,   
     5XCRORE,XMH2O,XMCO2,XMCACO,XMMGCA,XMCAOH,TFWL,TFWS,TBWL,TBWS,      
     6TMCAL,TMCAS,TCAL,TCAS,TFOS,TFOL,TFMS,TFML,XVISC(28),SVISC(28),    
     7XMOL(28),FMMOL(28),ROM(28),ROMLIQ(28),AEQM(28,2),BEQM(28,2),
     8CEQM(28,2),ECL,ECS,ECAL,ECAS,EMCAL,EMCAS,EBWL,EBWS,EFWL,EFWS,    
     9STEF,GRAV,PI,TCS,TCL,CCL,CCS,RMASSL,WPCC,WPM,WPA,WPCS,ROC,RMASSS,   
     1ANGSHL,RSLAGL,RSLAGS,HNODT,VFAV,VGAV,QXAV,XWTSS(16),  
     2TSCS(2),TSCL(2),ESCS(2),ESCL(2),CCSS(2),CCSL(2),ROSTLS,ROSTLL,
     3XFRGAS,HMINC,TST(99),TSTOP(99),AINTP(99),BINTP(99),DRATIO(999),
     4XBCN(999),XDCN(999),XBLT(15),ADEC(99),BDEC(99),APOUR(16,99),
     5BPOUR(16,99),XWTC(14),BWIDTH,THCKCV,TMBOIL,TEBOIL,VFINT,ANGFAN,
     6ALPMAX,THSHL,XFCABL,XNDMIN,DVMX,DAVMX,DEAVMX,DEMX,TDC,QDCU,QDCUO2,
     7TSINJ,EINJ,DTINJ,TKINJ,ROEV,CPINJ,SURFT,VSINJ,EMINJ,TSINJO,EINJO,
     8DTINJO,TKINJO,ROEVO,CPINJO,SURFTO,VSINJO,EMINJO,XLEADE,ARSUM,
     9DBUBOX,UTRISE,TREMSH,DJET,DFALL,WEBER,FROUDE,XPSAITO,XPEPSTN,
     1FRAG,XMBEDT,XMBED(16),XLPENT,XLPENA,UJET,UFALL,HFALL,ERPV,
     2TJETT(99),DJETT(99),HWATP,XDOTJET,DVMXW,DAVMXW,DEMXW,DEAVMXW,
     3QJETW,XSTMJF,TINTSJF,ESAT,DRDOOR,DRANL,EI,QDCBUO2,QDCBU,
     4EBEDS,EBEDB
      IF(NADAB.EQ.0) GO TO 88
      HSHELL=0.D0
      GO TO 100
   88 CONTINUE
      ANFAR=(PI*ANGSHL)/180.D0  
      HTOT=HEIGHT/(1.D0-VOID)   
      HTOT=DMAX1(HTOT,HMINC)    
      HEV=2.D0*BWIDTH
      PR=ABS((UM*CM)/TKM)
      RENV=ABS((PM*HEV*V)/UM)   
      HSHELL=TKM/XLENSH
      IF(RENV.GT.0.D0) HSHELL=(1.1007D0*(RENV**.368D0)*(PR**.42D0)*TKM)/
     1HEV
      HFCONV=HSHELL   
      IF(NLOGSH.EQ.0) GO TO 100 
      HVAL=DMAX1(HEIGHT,HMINC)  
      HEV=HVAL/((1.D0-VOID)*COS(ANFAR))   
      ULIQ=17.D0*VG   
      IF(VG.GE.0.06) ULIQ=1.02  
      REUL=ABS((PM*HEV*ULIQ)/UM)
      HBUB=(.037*(REUL**.8)*(PR**.33)*TKM)/HEV      
      HSHELL=HBUB     
      IF(NLOGSH.EQ.2) HSHELL=HBUB+HFCONV  
  100 CONTINUE
      RETURN
      END